using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesMaestros
{
    public partial class F0006
    {
        public string Mcmcu { get; set; }
        public string Mcstyl { get; set; }
        public string Mcdc { get; set; }
        public string Mcldm { get; set; }
        public string Mcco { get; set; }
        public double? Mcan8 { get; set; }
        public double? Mcan8o { get; set; }
        public string Mccnty { get; set; }
        public string Mcadds { get; set; }
        public string Mcfmod { get; set; }
        public string Mcdl01 { get; set; }
        public string Mcdl02 { get; set; }
        public string Mcdl03 { get; set; }
        public string Mcdl04 { get; set; }
        public string Mcrp01 { get; set; }
        public string Mcrp02 { get; set; }
        public string Mcrp03 { get; set; }
        public string Mcrp04 { get; set; }
        public string Mcrp05 { get; set; }
        public string Mcrp06 { get; set; }
        public string Mcrp07 { get; set; }
        public string Mcrp08 { get; set; }
        public string Mcrp09 { get; set; }
        public string Mcrp10 { get; set; }
        public string Mcrp11 { get; set; }
        public string Mcrp12 { get; set; }
        public string Mcrp13 { get; set; }
        public string Mcrp14 { get; set; }
        public string Mcrp15 { get; set; }
        public string Mcrp16 { get; set; }
        public string Mcrp17 { get; set; }
        public string Mcrp18 { get; set; }
        public string Mcrp19 { get; set; }
        public string Mcrp20 { get; set; }
        public string Mcrp21 { get; set; }
        public string Mcrp22 { get; set; }
        public string Mcrp23 { get; set; }
        public string Mcrp24 { get; set; }
        public string Mcrp25 { get; set; }
        public string Mcrp26 { get; set; }
        public string Mcrp27 { get; set; }
        public string Mcrp28 { get; set; }
        public string Mcrp29 { get; set; }
        public string Mcrp30 { get; set; }
        public string Mcta { get; set; }
        public double? Mctxjs { get; set; }
        public string Mctxa1 { get; set; }
        public string Mcexr1 { get; set; }
        public string Mctc01 { get; set; }
        public string Mctc02 { get; set; }
        public string Mctc03 { get; set; }
        public string Mctc04 { get; set; }
        public string Mctc05 { get; set; }
        public string Mctc06 { get; set; }
        public string Mctc07 { get; set; }
        public string Mctc08 { get; set; }
        public string Mctc09 { get; set; }
        public string Mctc10 { get; set; }
        public string Mcnd01 { get; set; }
        public string Mcnd02 { get; set; }
        public string Mcnd03 { get; set; }
        public string Mcnd04 { get; set; }
        public string Mcnd05 { get; set; }
        public string Mcnd06 { get; set; }
        public string Mcnd07 { get; set; }
        public string Mcnd08 { get; set; }
        public string Mcnd09 { get; set; }
        public string Mcnd10 { get; set; }
        public string Mccc01 { get; set; }
        public string Mccc02 { get; set; }
        public string Mccc03 { get; set; }
        public string Mccc04 { get; set; }
        public string Mccc05 { get; set; }
        public string Mccc06 { get; set; }
        public string Mccc07 { get; set; }
        public string Mccc08 { get; set; }
        public string Mccc09 { get; set; }
        public string Mccc10 { get; set; }
        public string Mcpecc { get; set; }
        public string Mcals { get; set; }
        public string Mciss { get; set; }
        public string Mcglba { get; set; }
        public string Mcalcl { get; set; }
        public string Mclmth { get; set; }
        public double? Mclf { get; set; }
        public string Mcobj1 { get; set; }
        public string Mcobj2 { get; set; }
        public string Mcobj3 { get; set; }
        public string Mcsub1 { get; set; }
        public double? Mctou { get; set; }
        public string Mcsbli { get; set; }
        public double? Mcanpa { get; set; }
        public string Mcct { get; set; }
        public string Mccert { get; set; }
        public string Mcmcus { get; set; }
        public string Mcbtyp { get; set; }
        public double? Mcpc { get; set; }
        public double? Mcpca { get; set; }
        public double? Mcpcc { get; set; }
        public string Mcinta { get; set; }
        public string Mcintl { get; set; }
        public decimal? Mcd1j { get; set; }
        public decimal? Mcd2j { get; set; }
        public decimal? Mcd3j { get; set; }
        public decimal? Mcd4j { get; set; }
        public decimal? Mcd5j { get; set; }
        public decimal? Mcd6j { get; set; }
        public decimal? Mcfpdj { get; set; }
        public double? Mccac { get; set; }
        public double? Mcpac { get; set; }
        public string Mceeo { get; set; }
        public string Mcerc { get; set; }
        public string Mcuser { get; set; }
        public string Mcpid { get; set; }
        public decimal? Mcupmj { get; set; }
        public string Mcjobn { get; set; }
        public double? Mcupmt { get; set; }
        public string Mcbptp { get; set; }
        public string Mcapsb { get; set; }
        public string Mctsbu { get; set; }
    }
}
