using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesMaestros
{
    public partial class F0101
    {
        public double Aban8 { get; set; }
        public string Abalky { get; set; }
        public string Abtax { get; set; }
        public string Abalph { get; set; }
        public string Abdc { get; set; }
        public string Abmcu { get; set; }
        public string Absic { get; set; }
        public string Ablngp { get; set; }
        public string Abat1 { get; set; }
        public string Abcm { get; set; }
        public string Abtaxc { get; set; }
        public string Abat2 { get; set; }
        public string Abat3 { get; set; }
        public string Abat4 { get; set; }
        public string Abat5 { get; set; }
        public string Abatp { get; set; }
        public string Abatr { get; set; }
        public string Abatpr { get; set; }
        public string Abab3 { get; set; }
        public string Abate { get; set; }
        public string Absbli { get; set; }
        public decimal? Abeftb { get; set; }
        public double? Aban81 { get; set; }
        public double? Aban82 { get; set; }
        public double? Aban83 { get; set; }
        public double? Aban84 { get; set; }
        public double? Aban86 { get; set; }
        public double? Aban85 { get; set; }
        public string Abac01 { get; set; }
        public string Abac02 { get; set; }
        public string Abac03 { get; set; }
        public string Abac04 { get; set; }
        public string Abac05 { get; set; }
        public string Abac06 { get; set; }
        public string Abac07 { get; set; }
        public string Abac08 { get; set; }
        public string Abac09 { get; set; }
        public string Abac10 { get; set; }
        public string Abac11 { get; set; }
        public string Abac12 { get; set; }
        public string Abac13 { get; set; }
        public string Abac14 { get; set; }
        public string Abac15 { get; set; }
        public string Abac16 { get; set; }
        public string Abac17 { get; set; }
        public string Abac18 { get; set; }
        public string Abac19 { get; set; }
        public string Abac20 { get; set; }
        public string Abac21 { get; set; }
        public string Abac22 { get; set; }
        public string Abac23 { get; set; }
        public string Abac24 { get; set; }
        public string Abac25 { get; set; }
        public string Abac26 { get; set; }
        public string Abac27 { get; set; }
        public string Abac28 { get; set; }
        public string Abac29 { get; set; }
        public string Abac30 { get; set; }
        public string Abglba { get; set; }
        public double? Abpti { get; set; }
        public decimal? Abpdi { get; set; }
        public string Abmsga { get; set; }
        public string Abrmk { get; set; }
        public string Abtxct { get; set; }
        public string Abtx2 { get; set; }
        public string Abalp1 { get; set; }
        public string Aburcd { get; set; }
        public decimal? Aburdt { get; set; }
        public double? Aburat { get; set; }
        public double? Aburab { get; set; }
        public string Aburrf { get; set; }
        public string Abuser { get; set; }
        public string Abpid { get; set; }
        public decimal? Abupmj { get; set; }
        public string Abjobn { get; set; }
        public double? Abupmt { get; set; }
        public string Abprgf { get; set; }
        public string Absccltp { get; set; }
        public string Abticker { get; set; }
        public string Abexchg { get; set; }
        public string Abduns { get; set; }
        public string Abclass01 { get; set; }
        public string Abclass02 { get; set; }
        public string Abclass03 { get; set; }
        public string Abclass04 { get; set; }
        public string Abclass05 { get; set; }
        public double? Abnoe { get; set; }
        public double? Abgrowthr { get; set; }
        public string Abyearstar { get; set; }
        public string Abaempgp { get; set; }
        public string Abactin { get; set; }
        public string Abrevrng { get; set; }
        public double? Absyncs { get; set; }
        public double? Abperrs { get; set; }
        public double? Abcaad { get; set; }
    }
}
