using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesMooreve
{
    public partial class Complemento
    {
        public string Transaccion { get; set; }
        public double? Documento { get; set; }
        public double? Linea { get; set; }
        public double? Proveedor { get; set; }
        public double? Año { get; set; }
        public double? Mes { get; set; }
        public double? Fecha { get; set; }
        public string TipoDocRet { get; set; }
        public double? DocRet { get; set; }
        public double? Factura { get; set; }
        public double? Batch { get; set; }
        public double? Monto { get; set; }
        public double? PorcentajeRet { get; set; }
        public string TipodeRet { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
        public string F18 { get; set; }
        public string F19 { get; set; }
        public string F20 { get; set; }
        public string F21 { get; set; }
        public string F22 { get; set; }
        public string F23 { get; set; }
        public string F24 { get; set; }
        public string F25 { get; set; }
        public string F26 { get; set; }
        public string F27 { get; set; }
        public string F28 { get; set; }
        public string F29 { get; set; }
        public string F30 { get; set; }
        public string F31 { get; set; }
        public string F32 { get; set; }
        public string F33 { get; set; }
        public string F34 { get; set; }
        public string F35 { get; set; }
        public string F36 { get; set; }
        public string F37 { get; set; }
        public string F38 { get; set; }
        public string F39 { get; set; }
        public string F40 { get; set; }
        public string F41 { get; set; }
        public string F42 { get; set; }
        public string F43 { get; set; }
        public string F44 { get; set; }
        public string F45 { get; set; }
        public string F46 { get; set; }
        public string F47 { get; set; }
        public string F48 { get; set; }
        public string F49 { get; set; }
        public string F50 { get; set; }
        public string F51 { get; set; }
        public string F52 { get; set; }
        public string F53 { get; set; }
        public string F54 { get; set; }
        public string F55 { get; set; }
        public string F56 { get; set; }
        public string F57 { get; set; }
        public string F58 { get; set; }
        public string F59 { get; set; }
        public string F60 { get; set; }
        public string F61 { get; set; }
        public string F62 { get; set; }
        public string F63 { get; set; }
        public string F64 { get; set; }
        public string F65 { get; set; }
        public string F66 { get; set; }
        public string F67 { get; set; }
        public string F68 { get; set; }
        public string F69 { get; set; }
        public string F70 { get; set; }
        public string F71 { get; set; }
        public string F72 { get; set; }
        public string F73 { get; set; }
        public string F74 { get; set; }
        public string F75 { get; set; }
        public string F76 { get; set; }
        public string F77 { get; set; }
        public string F78 { get; set; }
        public string F79 { get; set; }
        public string F80 { get; set; }
        public string F81 { get; set; }
        public string F82 { get; set; }
        public string F83 { get; set; }
        public string F84 { get; set; }
        public string F85 { get; set; }
        public string F86 { get; set; }
        public string F87 { get; set; }
        public string F88 { get; set; }
        public string F89 { get; set; }
        public string F90 { get; set; }
        public string F91 { get; set; }
        public string F92 { get; set; }
        public string F93 { get; set; }
        public string F94 { get; set; }
        public string F95 { get; set; }
        public string F96 { get; set; }
        public string F97 { get; set; }
        public string F98 { get; set; }
        public string F99 { get; set; }
        public string F100 { get; set; }
        public string F101 { get; set; }
        public string F102 { get; set; }
        public string F103 { get; set; }
        public string F104 { get; set; }
        public string F105 { get; set; }
        public string F106 { get; set; }
        public string F107 { get; set; }
        public string F108 { get; set; }
        public string F109 { get; set; }
        public string F110 { get; set; }
        public string F111 { get; set; }
        public string F112 { get; set; }
        public string F113 { get; set; }
        public string F114 { get; set; }
        public string F115 { get; set; }
        public string F116 { get; set; }
        public string F117 { get; set; }
        public string F118 { get; set; }
        public string F119 { get; set; }
        public string F120 { get; set; }
        public string F121 { get; set; }
        public string F122 { get; set; }
        public string F123 { get; set; }
        public string F124 { get; set; }
        public string F125 { get; set; }
        public string F126 { get; set; }
        public string F127 { get; set; }
        public string F128 { get; set; }
        public string F129 { get; set; }
        public string F130 { get; set; }
        public string F131 { get; set; }
        public string F132 { get; set; }
        public string F133 { get; set; }
        public string F134 { get; set; }
        public string F135 { get; set; }
        public string F136 { get; set; }
        public string F137 { get; set; }
        public string F138 { get; set; }
        public string F139 { get; set; }
        public string F140 { get; set; }
        public string F141 { get; set; }
        public string F142 { get; set; }
        public string F143 { get; set; }
        public string F144 { get; set; }
        public string F145 { get; set; }
        public string F146 { get; set; }
        public string F147 { get; set; }
        public string F148 { get; set; }
        public string F149 { get; set; }
        public string F150 { get; set; }
        public string F151 { get; set; }
        public string F152 { get; set; }
        public string F153 { get; set; }
        public string F154 { get; set; }
        public string F155 { get; set; }
        public string F156 { get; set; }
        public string F157 { get; set; }
        public string F158 { get; set; }
        public string F159 { get; set; }
        public string F160 { get; set; }
        public string F161 { get; set; }
        public string F162 { get; set; }
        public string F163 { get; set; }
        public string F164 { get; set; }
        public string F165 { get; set; }
        public string F166 { get; set; }
        public string F167 { get; set; }
        public string F168 { get; set; }
        public string F169 { get; set; }
        public string F170 { get; set; }
        public string F171 { get; set; }
        public string F172 { get; set; }
        public string F173 { get; set; }
        public string F174 { get; set; }
        public string F175 { get; set; }
        public string F176 { get; set; }
        public string F177 { get; set; }
        public string F178 { get; set; }
        public string F179 { get; set; }
        public string F180 { get; set; }
        public string F181 { get; set; }
        public string F182 { get; set; }
        public string F183 { get; set; }
        public string F184 { get; set; }
        public string F185 { get; set; }
        public string F186 { get; set; }
        public string F187 { get; set; }
        public string F188 { get; set; }
        public string F189 { get; set; }
        public string F190 { get; set; }
        public string F191 { get; set; }
        public string F192 { get; set; }
        public string F193 { get; set; }
        public string F194 { get; set; }
        public string F195 { get; set; }
        public string F196 { get; set; }
        public string F197 { get; set; }
        public string F198 { get; set; }
        public string F199 { get; set; }
        public string F200 { get; set; }
        public string F201 { get; set; }
        public string F202 { get; set; }
        public string F203 { get; set; }
        public string F204 { get; set; }
        public string F205 { get; set; }
        public string F206 { get; set; }
        public string F207 { get; set; }
        public string F208 { get; set; }
        public string F209 { get; set; }
        public string F210 { get; set; }
        public string F211 { get; set; }
        public string F212 { get; set; }
        public string F213 { get; set; }
        public string F214 { get; set; }
        public string F215 { get; set; }
        public string F216 { get; set; }
        public string F217 { get; set; }
        public string F218 { get; set; }
        public string F219 { get; set; }
        public string F220 { get; set; }
        public string F221 { get; set; }
        public string F222 { get; set; }
        public string F223 { get; set; }
        public string F224 { get; set; }
        public string F225 { get; set; }
        public string F226 { get; set; }
        public string F227 { get; set; }
        public string F228 { get; set; }
        public string F229 { get; set; }
        public string F230 { get; set; }
        public string F231 { get; set; }
        public string F232 { get; set; }
        public string F233 { get; set; }
        public string F234 { get; set; }
        public string F235 { get; set; }
        public string F236 { get; set; }
        public string F237 { get; set; }
        public string F238 { get; set; }
        public string F239 { get; set; }
        public string F240 { get; set; }
        public string F241 { get; set; }
        public string F242 { get; set; }
        public string F243 { get; set; }
        public string F244 { get; set; }
        public string F245 { get; set; }
        public string F246 { get; set; }
        public string F247 { get; set; }
        public string F248 { get; set; }
        public string F249 { get; set; }
        public string F250 { get; set; }
        public string F251 { get; set; }
        public string F252 { get; set; }
        public string F253 { get; set; }
        public string F254 { get; set; }
        public string F255 { get; set; }
        public string F256 { get; set; }
    }
}
