using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesMooreve
{
    public partial class Winy252
    {
        public decimal Recnum { get; set; }
        public string RegistroTribut { get; set; }
        public short CentroFact { get; set; }
        public string Usuario { get; set; }
        public int Cliente { get; set; }
        public long Orden { get; set; }
        public string OrdenCompra { get; set; }
        public string CredConta { get; set; }
        public string Vendedor { get; set; }
        public decimal Flete { get; set; }
        public decimal Seguro { get; set; }
        public decimal OtroGasto1 { get; set; }
        public decimal OtroGasto2 { get; set; }
        public decimal TipoCambio { get; set; }
        public decimal ValorLista { get; set; }
        public decimal? ValorListad { get; set; }
        public decimal ValorVenta { get; set; }
        public decimal? ValorVentad { get; set; }
        public DateTime FechaFactura { get; set; }
        public string Dolar { get; set; }
        public string Transmision { get; set; }
        public string Nombre { get; set; }
        public string FlagComision { get; set; }
        public string Supervisor { get; set; }
        public string TotalParcial { get; set; }
        public short CodigoRepetici { get; set; }
        public DateTime FechaRecibCli { get; set; }
        public int FactFinal { get; set; }
        public string Anulada { get; set; }
        public int? MesFactura { get; set; }
        public int? AnoFactura { get; set; }
        public string VendGestion { get; set; }
        public string MultiplesEmb { get; set; }
        public short CondicionPago { get; set; }
        public string DireccFiscal { get; set; }
        public short UnidadFacturar { get; set; }
        public string DireccionFact1 { get; set; }
        public string DireccionFact2 { get; set; }
        public string NombreFact { get; set; }
        public string DireccionEmb1 { get; set; }
        public string DireccionEmb2 { get; set; }
        public string NombreEmb { get; set; }
        public string RifFact { get; set; }
        public string RifEmb { get; set; }
        public short Imp { get; set; }
        public long NitFact { get; set; }
        public long NitEmb { get; set; }
        public int Cajas { get; set; }
        public string DireccionFact3 { get; set; }
        public string DireccionEmb3 { get; set; }
        public int NroNc { get; set; }
        public DateTime FechaDespacho { get; set; }
        public short Copy { get; set; }
        public decimal TasaImpuesto { get; set; }
        public string Observacion1 { get; set; }
        public string Observacion2 { get; set; }
        public string Observacion3 { get; set; }
        public string Fiscal { get; set; }
        public string FlagImpreso { get; set; }
        public string ImpStock { get; set; }
        public int FacturaRepetir { get; set; }
        public int NcFacturar { get; set; }
        public short CondPago { get; set; }
        public decimal? ImpuestoDol { get; set; }
        public int Anticipo { get; set; }
        public decimal SdoAnticipo { get; set; }
        public short LineaAnt { get; set; }
        public short NuevaLineaAnt { get; set; }
        public decimal TasaAnticipo { get; set; }
        public decimal SdoAnticipoDo { get; set; }
        public string FactAdelantada { get; set; }
        public long NroControl { get; set; }
        public string Estado { get; set; }
        public string Municipio { get; set; }
        public long? JobId { get; set; }
        public string ObsCobranzas1 { get; set; }
        public string ObsCobranzas2 { get; set; }
        public string ObsCobranzas3 { get; set; }
        public string ObsCobranzas4 { get; set; }
        public string ColetillaInd1 { get; set; }
        public string ColetillaInd2 { get; set; }
        public string ColetillaInd3 { get; set; }
        public string ColetillaInd4 { get; set; }
        public decimal? OtroGasto1R { get; set; }
        public decimal? ValorListaR { get; set; }
        public decimal? ValorListadR { get; set; }
        public decimal? ValorVentaR { get; set; }
        public decimal? ValorVentadR { get; set; }
        public decimal? CantResumen { get; set; }
        public string DescResumen1 { get; set; }
        public string DescResumen2 { get; set; }
        public string UndResumen { get; set; }
    }
}
