using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesMooreve
{
    public partial class Winy249
    {
        public decimal Recnum { get; set; }
        public string RegistroTribut { get; set; }
        public short CentroFact { get; set; }
        public string Usuario { get; set; }
        public long Orden { get; set; }
        public long JobId { get; set; }
        public decimal? Copy { get; set; }
        public string Articulo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal? Impuesto1 { get; set; }
        public decimal Impuesto2 { get; set; }
        public decimal ValorVenta { get; set; }
        public decimal? ValorVentad { get; set; }
        public decimal ValorLista { get; set; }
        public decimal? ValorListad { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal PrecioLista { get; set; }
        public string Descripcion1 { get; set; }
        public string Descripcion2 { get; set; }
        public string TipoProducto { get; set; }
        public string FlagImprenta { get; set; }
        public string TotalParcial { get; set; }
        public int NoEntrega { get; set; }
        public DateTime FechaFactura { get; set; }
        public DateTime? FechaOrden { get; set; }
        public string Pais { get; set; }
        public string LineaProduccio { get; set; }
        public string FamiliaProducc { get; set; }
        public DateTime? FecRecPlaneac { get; set; }
        public string FlagTipoJob { get; set; }
        public DateTime? FecComproClte { get; set; }
        public string OrigenProducto { get; set; }
        public string FlagRetenido { get; set; }
        public string FlagTipoOrden { get; set; }
        public string DireccionFact { get; set; }
        public string NombreFact { get; set; }
        public string RifFact { get; set; }
        public string DireccionEmb { get; set; }
        public string NombreEmb { get; set; }
        public string RifEmb { get; set; }
        public decimal Iva { get; set; }
        public string Linea1 { get; set; }
        public string Partes { get; set; }
        public string MetodoPrecio1 { get; set; }
        public string TipoPapel { get; set; }
        public string Lipamepa { get; set; }
        public string Familia { get; set; }
        public string UnidadFacturar { get; set; }
        public decimal FormasUnidad { get; set; }
        public short Bultos { get; set; }
        public string PrefijoDesde { get; set; }
        public long NumeroDesde { get; set; }
        public string SufijoDesde { get; set; }
        public string PrefijoHasta { get; set; }
        public long NumeroHasta { get; set; }
        public string SufijoHasta { get; set; }
        public string FlagFaltante { get; set; }
        public int FormasBajotiro { get; set; }
        public string Millares { get; set; }
        public string CtaLista { get; set; }
        public string CtaConc { get; set; }
        public string Estadisticas { get; set; }
        public decimal? VentaUniDol { get; set; }
        public decimal? ListaUniDol { get; set; }
        public decimal ImpuestoDol { get; set; }
        public decimal? TipoCambio { get; set; }
        public decimal? CantEntregar { get; set; }
        public string PrefijoDesdeEnt { get; set; }
        public long? NumeroDesdeEnt { get; set; }
        public string SufijoDesdeEnt { get; set; }
        public string PrefijoHastaEnt { get; set; }
        public long? NumeroHastaEnt { get; set; }
        public string SufijoHastaEnt { get; set; }
        public decimal? Unidadesfact { get; set; }
        public decimal? Unidadesent { get; set; }
        public decimal? Preciounidad { get; set; }
        public decimal? Impuesto1R { get; set; }
        public decimal? ValorVentaR { get; set; }
        public decimal? ValorVentadR { get; set; }
        public decimal? ValorListaR { get; set; }
        public decimal? ValorListadR { get; set; }
        public decimal? RemisionOfi { get; set; }
        public string GeneraDespacho { get; set; }
        public string ImpStock { get; set; }
        public DateTime? FechaPrometida { get; set; }
        public decimal? PreciounidadR { get; set; }
        public decimal? FacturaAsociada { get; set; }
        public DateTime? FechaProg { get; set; }
        public int? BultoDesp { get; set; }
        public decimal? KiloBulto { get; set; }
        public int? BultoTran { get; set; }
        public string Almacen { get; set; }
        public decimal? PorcMcPapel { get; set; }
        public decimal? PorcMcFinan { get; set; }
        public decimal? BsMcPapel { get; set; }
        public decimal? BsMcFinan { get; set; }
        public decimal? PorcMcPapelsc { get; set; }
        public decimal? PorcMcFinansc { get; set; }
        public decimal? BsMcPapelsc { get; set; }
        public decimal? BsMcFinansc { get; set; }
        public string PrefijoCli { get; set; }
        public string SufijoCli { get; set; }
        public string NumCliDesde { get; set; }
        public string NumCliHasta { get; set; }
        public string PrefijoCliE { get; set; }
        public string SufijoCliE { get; set; }
        public string NumCliDesdeE { get; set; }
        public string NumCliHastaE { get; set; }
        public int? FacturaRepetir { get; set; }
        public int? NcFacturar { get; set; }
        public decimal? Ivarefact { get; set; }
        public long IdPrelista { get; set; }
    }
}
