using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesMooreve
{
    public partial class Wsmy106
    {
        public decimal Recnum { get; set; }
        public long Orden { get; set; }
        public string Cotizacion { get; set; }
        public string Vendedor { get; set; }
        public string Region { get; set; }
        public short? Division { get; set; }
        public string CodProduc { get; set; }
        public string LineaProduc { get; set; }
        public string FamilProduc { get; set; }
        public short? TipoProduc { get; set; }
        public short? EntBase { get; set; }
        public short? NumBase { get; set; }
        public short? DenBase { get; set; }
        public string SujOpacSplock { get; set; }
        public string SujOpacIzq { get; set; }
        public string SujOpacDer { get; set; }
        public string SujCarbSplk { get; set; }
        public string SujOpacSpflex { get; set; }
        public string SujOpacSpfI { get; set; }
        public string SujOpacSpfD { get; set; }
        public string SujCarbEngoma { get; set; }
        public string SujCarbIzq { get; set; }
        public string SujCarbonDer { get; set; }
        public string PerfTalonOpac { get; set; }
        public string PrfTalOpCarb { get; set; }
        public string PerfTalonIzq { get; set; }
        public string PerfTalonDer { get; set; }
        public string PerfTalonNin { get; set; }
        public string SpdsetSuelto { get; set; }
        public string SpsetEngomado { get; set; }
        public string SpsetEngrapad { get; set; }
        public string SpsetEngraTal { get; set; }
        public string SpsetEngraOpu { get; set; }
        public string SpsetCaratula { get; set; }
        public string SpsetGrupos { get; set; }
        public string WizPoncheArch { get; set; }
        public string PoncheEnHojas { get; set; }
        public long? PonchHojaNEl { get; set; }
        public long? PonchHojaNAl { get; set; }
        public long? CantPonche { get; set; }
        public long? NumDiamPonche { get; set; }
        public long? DenDiamPonche { get; set; }
        public long? ClasePonche { get; set; }
        public string DistanCcPonch { get; set; }
        public long? PosicionPonche { get; set; }
        public long? GruposSpidiset { get; set; }
        public string MedidaEngrap { get; set; }
        public string KeenEdge { get; set; }
        public string Reinsercion { get; set; }
        public string SobrePago { get; set; }
        public string Speedmailer { get; set; }
        public string Seguridad { get; set; }
        public string SpotCarbon { get; set; }
        public string CodigBarras { get; set; }
        public string Micr { get; set; }
        public string TransferTape { get; set; }
        public decimal? TasaCambio { get; set; }
        public decimal? NumForma { get; set; }
        public long? OrdenAnterior { get; set; }
        public string Descripcion { get; set; }
        public string AtencionA { get; set; }
        public short? DiaRegistro { get; set; }
        public short? MesRegistro { get; set; }
        public short? AnoRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public DateTime? FechaTomado { get; set; }
        public DateTime? FechaNegocio { get; set; }
        public string InstruccProduc { get; set; }
        public short? OperacionBasic { get; set; }
        public string OrdenCompra { get; set; }
        public string PersonaRespons { get; set; }
        public string CargoResponsab { get; set; }
        public DateTime? FechaAceptada { get; set; }
        public short? OpcionAceptada { get; set; }
        public short? RazonAceptada { get; set; }
        public string Estado { get; set; }
        public string Concesion { get; set; }
        public string Creditos { get; set; }
        public string ComentDeCredt { get; set; }
        public string Supervisor { get; set; }
        public DateTime? ExistenciaDura { get; set; }
        public DateTime? FechaVendedor { get; set; }
        public DateTime? FechaConcesion { get; set; }
        public DateTime? FechaCredito { get; set; }
        public DateTime? FechaVenta { get; set; }
        public string Rechazada { get; set; }
        public string ObservaciRecha { get; set; }
        public string ProcesoBcs { get; set; }
        public long? CantidadOrigin { get; set; }
        public decimal? ListaOriginal { get; set; }
        public decimal? VentaOriginal { get; set; }
        public long? FlagContrato { get; set; }
        public string FlagPrimEntre { get; set; }
        public string FlagReplicar { get; set; }
        public DateTime FechaDeOrden { get; set; }
        public string OrdenSiguiente { get; set; }
        public string TipoProduccion { get; set; }
        public string PerMarDer { get; set; }
        public string PerMarIzq { get; set; }
        public string TipoRechazo { get; set; }
        public string Nc { get; set; }
        public string PerfTalonIzqn { get; set; }
        public string PerfTalonDern { get; set; }
        public string TalonCabeza { get; set; }
        public string TalonPie { get; set; }
        public decimal? VentaTotDol { get; set; }
        public decimal? ListaTotDol { get; set; }
        public decimal? VentaUniDol { get; set; }
        public decimal? ListaUniDol { get; set; }
        public decimal? TasaNegociacio { get; set; }
        public DateTime? FechaTasa { get; set; }
        public string TasaManual { get; set; }
        public string SiColetilla { get; set; }
        public string SiIndexado { get; set; }
        public string SiDolares { get; set; }
        public string Correo { get; set; }
        public string CodTeleop { get; set; }
        public decimal? RtasaCambio { get; set; }
        public decimal? RlistaOriginal { get; set; }
        public decimal? RventaOriginal { get; set; }
        public decimal? RtasaNegociacio { get; set; }
    }
}
