using System;
using System.Collections.Generic;

namespace AppService.Core.Entities
{
    public partial class Ctmy034
    {
        public decimal Recnum { get; set; }
        public int NumeroPedido { get; set; }
        public string Vendedor { get; set; }
        public string CodProducto { get; set; }
        public string Medida { get; set; }
        public string DescProducto { get; set; }
        public int CantPedida { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal TotalVenta { get; set; }
        public decimal PrecioLista { get; set; }
        public decimal TotalLista { get; set; }
        public decimal PorcentConces { get; set; }
        public decimal CantFacturada { get; set; }
        public string TipoProducto { get; set; }
        public string LineaProducto { get; set; }
        public string FamiliaProduct { get; set; }
        public short LineaIncoming { get; set; }
        public string VendGestion { get; set; }
        public long Orden { get; set; }
        public string Presentacion { get; set; }
        public string OrigenProducto { get; set; }
        public string DireccionFact { get; set; }
        public string NombreFact { get; set; }
        public string RifFact { get; set; }
        public string DireccionEmb { get; set; }
        public string NombreEmb { get; set; }
        public string RifEmb { get; set; }
        public decimal CtdEntregada { get; set; }
        public decimal UnitListaDol { get; set; }
        public decimal UnitVentaDol { get; set; }
        public decimal Tasa { get; set; }
        public decimal VentaTotDol { get; set; }
        public decimal ListaTotDol { get; set; }
        public int RemisionOfic { get; set; }
        public DateTime? FechaRemision { get; set; }
        public long CtdDespOfic { get; set; }
        public string PasoSql { get; set; }
        public string Anulado { get; set; }
        public decimal? CodResponsable { get; set; }
        public string Excepcion { get; set; }
        public decimal? PorcCom { get; set; }
        public decimal? CodAplicacion { get; set; }
        public decimal? Bsmc { get; set; }
        public decimal? Pormc { get; set; }
        public int? TipoIva { get; set; }
        public decimal? PorcMcPapel { get; set; }
        public decimal? PorcMcFinan { get; set; }
        public decimal? BsMcPapel { get; set; }
        public decimal? BsMcFinan { get; set; }
        public decimal? PorcMcPapelsc { get; set; }
        public decimal? PorcMcFinansc { get; set; }
        public decimal? BsMcPapelsc { get; set; }
        public decimal? BsMcFinansc { get; set; }
        public string Nocalculamc { get; set; }
        public decimal? AnticipoJde { get; set; }
        public decimal? LineaAntJde { get; set; }
        public decimal? RprecioVenta { get; set; }
        public decimal? RtotalVenta { get; set; }
        public decimal? RprecioLista { get; set; }
        public decimal? RtotalLista { get; set; }
        public decimal? Rtasa { get; set; }
        public decimal? Rbsmc { get; set; }
        public decimal? RbsMcPapel { get; set; }
        public decimal? RbsMcFinan { get; set; }
        public decimal? RbsMcPapelsc { get; set; }
        public decimal? RbsMcFinansc { get; set; }
        public decimal? Longitudmascara { get; set; }
        public string Seriecdesde { get; set; }
        public string Seriechasta { get; set; }
        public string Controldesde { get; set; }
        public string Controlhasta { get; set; }
        public string Seriefdesde { get; set; }
        public string Seriefhasta { get; set; }
        public string Formatodesde { get; set; }
        public string Formatohasta { get; set; }
        public string Tipodocumento { get; set; }
        public string Fiscal { get; set; }
        public string Sdkcoo { get; set; }
        public decimal? Sddoco { get; set; }
        public string Sddcto { get; set; }
        public string Sdlnid { get; set; }
        public string IvaJde { get; set; }
        public decimal? Maquina { get; set; }
        public decimal? HorasMaquina { get; set; }
        public string Papel { get; set; }
        public decimal? EbitPorc { get; set; }
        public decimal? EbitBs { get; set; }
        public string IdSolicitud { get; set; }
        public string RecalcularMargen { get; set; }
        public int? Año { get; set; }
        public int? Mes { get; set; }
        public decimal? IdSolicitud2 { get; set; }
        public string Codigocaja { get; set; }
        public int Cantidadcajasempaques { get; set; }
        public decimal Largoempaque { get; set; }
        public decimal Altoempaque { get; set; }
        public decimal Anchoempaque { get; set; }
        public string Equipoupdate { get; set; }
        public string Usuarioupdate { get; set; }
        public DateTime? Fechaupdate { get; set; }
        public decimal? PorcIva { get; set; }
    }
}
