using System;
using System.Collections.Generic;

namespace AppService.Core.Entities
{
    public partial class F03b11
    {
        public double Rpdoc { get; set; }
        public string Rpdct { get; set; }
        public string Rpkco { get; set; }
        public string Rpsfx { get; set; }
        public double? Rpan8 { get; set; }
        public decimal? Rpdgj { get; set; }
        public decimal? Rpdivj { get; set; }
        public string Rpicut { get; set; }
        public double? Rpicu { get; set; }
        public decimal? Rpdicj { get; set; }
        public double? Rpfy { get; set; }
        public double? Rpctry { get; set; }
        public double? Rppn { get; set; }
        public string Rpco { get; set; }
        public string Rpglc { get; set; }
        public string Rpaid { get; set; }
        public double? Rppa8 { get; set; }
        public double? Rpan8j { get; set; }
        public double? Rppyr { get; set; }
        public string Rppost { get; set; }
        public string Rpistr { get; set; }
        public string Rpbalj { get; set; }
        public string Rppst { get; set; }
        public double? Rpag { get; set; }
        public double? Rpaap { get; set; }
        public double? Rpadsc { get; set; }
        public double? Rpadsa { get; set; }
        public double? Rpatxa { get; set; }
        public double? Rpatxn { get; set; }
        public double? Rpstam { get; set; }
        public string Rpbcrc { get; set; }
        public string Rpcrrm { get; set; }
        public string Rpcrcd { get; set; }
        public double? Rpcrr { get; set; }
        public string Rpdmcd { get; set; }
        public double? Rpacr { get; set; }
        public double? Rpfap { get; set; }
        public double? Rpcds { get; set; }
        public double? Rpcdsa { get; set; }
        public double? Rpctxa { get; set; }
        public double? Rpctxn { get; set; }
        public double? Rpctam { get; set; }
        public string Rptxa1 { get; set; }
        public string Rpexr1 { get; set; }
        public decimal? Rpdsvj { get; set; }
        public string Rpglba { get; set; }
        public string Rpam { get; set; }
        public string Rpaid2 { get; set; }
        public string Rpam2 { get; set; }
        public string Rpmcu { get; set; }
        public string Rpobj { get; set; }
        public string Rpsub { get; set; }
        public string Rpsblt { get; set; }
        public string Rpsbl { get; set; }
        public string Rpptc { get; set; }
        public decimal? Rpddj { get; set; }
        public decimal? Rpddnj { get; set; }
        public decimal? Rprddj { get; set; }
        public decimal? Rprdsj { get; set; }
        public decimal? Rplfcj { get; set; }
        public decimal? Rpsmtj { get; set; }
        public string Rpnbrr { get; set; }
        public string Rprdrl { get; set; }
        public double? Rprmds { get; set; }
        public string Rpcoll { get; set; }
        public string Rpcorc { get; set; }
        public string Rpafc { get; set; }
        public string Rpdnlt { get; set; }
        public string Rprsco { get; set; }
        public double? Rpodoc { get; set; }
        public string Rpodct { get; set; }
        public string Rpokco { get; set; }
        public string Rposfx { get; set; }
        public string Rpvinv { get; set; }
        public string Rppo { get; set; }
        public string Rppdct { get; set; }
        public string Rppkco { get; set; }
        public string Rpdcto { get; set; }
        public double? Rplnid { get; set; }
        public double? Rpsdoc { get; set; }
        public string Rpsdct { get; set; }
        public string Rpskco { get; set; }
        public string Rpsfxo { get; set; }
        public decimal? Rpvldt { get; set; }
        public double? Rpcmc1 { get; set; }
        public string Rpvr01 { get; set; }
        public string Rpunit { get; set; }
        public string Rpmcu2 { get; set; }
        public string Rprmk { get; set; }
        public string Rpalph { get; set; }
        public string Rprf { get; set; }
        public double? Rpdrf { get; set; }
        public string Rpctl { get; set; }
        public string Rpfnlp { get; set; }
        public double? Rpitm { get; set; }
        public double? Rpu { get; set; }
        public string Rpum { get; set; }
        public string Rpalt6 { get; set; }
        public string Rpryin { get; set; }
        public decimal? Rpvdgj { get; set; }
        public string Rpvod { get; set; }
        public string Rprp1 { get; set; }
        public string Rprp2 { get; set; }
        public string Rprp3 { get; set; }
        public string Rpar01 { get; set; }
        public string Rpar02 { get; set; }
        public string Rpar03 { get; set; }
        public string Rpar04 { get; set; }
        public string Rpar05 { get; set; }
        public string Rpar06 { get; set; }
        public string Rpar07 { get; set; }
        public string Rpar08 { get; set; }
        public string Rpar09 { get; set; }
        public string Rpar10 { get; set; }
        public string Rpistc { get; set; }
        public double? Rppyid { get; set; }
        public string Rpurc1 { get; set; }
        public decimal? Rpurdt { get; set; }
        public double? Rpurat { get; set; }
        public double? Rpurab { get; set; }
        public string Rpurrf { get; set; }
        public double? Rprnid { get; set; }
        public decimal? Rpppdi { get; set; }
        public string Rptorg { get; set; }
        public string Rpuser { get; set; }
        public decimal? Rpjcl { get; set; }
        public string Rppid { get; set; }
        public decimal? Rpupmj { get; set; }
        public double? Rpupmt { get; set; }
        public string Rpddex { get; set; }
        public string Rpjobn { get; set; }
        public double? Rphcrr { get; set; }
        public decimal? Rphdgj { get; set; }
        public double? Rpshpn { get; set; }
        public string Rpdtxs { get; set; }
        public string Rpomod { get; set; }
        public string Rpclmg { get; set; }
        public string Rpcmgr { get; set; }
        public double? Rpatad { get; set; }
        public double? Rpctad { get; set; }
        public double? Rpnrta { get; set; }
        public double? Rpfnrt { get; set; }
        public string Rpprgf { get; set; }
        public string Rpgfl1 { get; set; }
        public string Rpgfl2 { get; set; }
        public double? Rpdoco { get; set; }
        public string Rpkcoo { get; set; }
        public string Rpsotf { get; set; }
        public decimal? Rpdtpb { get; set; }
        public decimal? Rperdj { get; set; }
        public double? Rppwpg { get; set; }
        public double? Rpnettcid { get; set; }
        public double? Rpnetdoc { get; set; }
        public double? Rpnetrc5 { get; set; }
        public string Rpnetst { get; set; }
        public decimal? Rpajcl { get; set; }
        public DateTime? Actualizacion { get; set; }
        public string Transferir { get; set; }
        public string Mensaje { get; set; }
        public decimal Id { get; set; }
        public decimal? Dias { get; set; }
        public DateTime? FechaFoto { get; set; }
        public decimal? SaldoFoto { get; set; }
        public decimal? PorcFoto { get; set; }
        public DateTime? VencimientoEntrega { get; set; }
    }
}
