using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class AdrcTemp
    {
        public string Client { get; set; }
        public string Addrnumber { get; set; }
        public string DateFrom { get; set; }
        public string Nation { get; set; }
        public string DateTo { get; set; }
        public string Title { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Name4 { get; set; }
        public string NameText { get; set; }
        public string NameCo { get; set; }
        public string City1 { get; set; }
        public string City2 { get; set; }
        public string CityCode { get; set; }
        public string CitypCode { get; set; }
        public string HomeCity { get; set; }
        public string CityhCode { get; set; }
        public string Chckstatus { get; set; }
        public string Regiogroup { get; set; }
        public string PostCode1 { get; set; }
        public string PostCode2 { get; set; }
        public string PostCode3 { get; set; }
        public string Pcode1Ext { get; set; }
        public string Pcode2Ext { get; set; }
        public string Pcode3Ext { get; set; }
        public string PoBox { get; set; }
        public string DontUseP { get; set; }
        public string PoBoxNum { get; set; }
        public string PoBoxLoc { get; set; }
        public string CityCode2 { get; set; }
        public string PoBoxReg { get; set; }
        public string PoBoxCty { get; set; }
        public string Postalarea { get; set; }
        public string Transpzone { get; set; }
        public string Street { get; set; }
        public string DontUseS { get; set; }
        public string Streetcode { get; set; }
        public string Streetabbr { get; set; }
        public string HouseNum1 { get; set; }
        public string HouseNum2 { get; set; }
        public string HouseNum3 { get; set; }
        public string StrSuppl1 { get; set; }
        public string StrSuppl2 { get; set; }
        public string StrSuppl3 { get; set; }
        public string Location { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public string Roomnumber { get; set; }
        public string Country { get; set; }
        public string Langu { get; set; }
        public string Region { get; set; }
        public string AddrGroup { get; set; }
        public string Flaggroups { get; set; }
        public string PersAddr { get; set; }
        public string Sort1 { get; set; }
        public string Sort2 { get; set; }
        public string SortPhn { get; set; }
        public string DefltComm { get; set; }
        public string TelNumber { get; set; }
        public string TelExtens { get; set; }
        public string FaxNumber { get; set; }
        public string FaxExtens { get; set; }
        public string Flagcomm2 { get; set; }
        public string Flagcomm3 { get; set; }
        public string Flagcomm4 { get; set; }
        public string Flagcomm5 { get; set; }
        public string Flagcomm6 { get; set; }
        public string Flagcomm7 { get; set; }
        public string Flagcomm8 { get; set; }
        public string Flagcomm9 { get; set; }
        public string Flagcomm10 { get; set; }
        public string Flagcomm11 { get; set; }
        public string Flagcomm12 { get; set; }
        public string Flagcomm13 { get; set; }
        public string Addrorigin { get; set; }
        public string McName1 { get; set; }
        public string McCity1 { get; set; }
        public string McStreet { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string TimeZone { get; set; }
        public string Taxjurcode { get; set; }
        public string AddressId { get; set; }
        public string LanguCrea { get; set; }
        public byte[] AdrcUuid { get; set; }
        public string UuidBelated { get; set; }
        public string IdCategory { get; set; }
        public string AdrcErrStatus { get; set; }
        public string PoBoxLobby { get; set; }
        public string DeliServType { get; set; }
        public string DeliServNumber { get; set; }
        public string CountyCode { get; set; }
        public string County { get; set; }
        public string TownshipCode { get; set; }
        public string Township { get; set; }
        public string McCounty { get; set; }
        public string McTownship { get; set; }
        public string Xpcpt { get; set; }
    }
}
