using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class BkpfTemp
    {
        public string Mandt { get; set; }
        public string Bukrs { get; set; }
        public string Belnr { get; set; }
        public string Gjahr { get; set; }
        public string Blart { get; set; }
        public string Bldat { get; set; }
        public string Budat { get; set; }
        public string Monat { get; set; }
        public string Cpudt { get; set; }
        public string Cputm { get; set; }
        public string Aedat { get; set; }
        public string Upddt { get; set; }
        public string Wwert { get; set; }
        public string Usnam { get; set; }
        public string Tcode { get; set; }
        public string Bvorg { get; set; }
        public string Xblnr { get; set; }
        public string Dbblg { get; set; }
        public string Stblg { get; set; }
        public string Stjah { get; set; }
        public string Bktxt { get; set; }
        public string Waers { get; set; }
        public decimal Kursf { get; set; }
        public string Kzwrs { get; set; }
        public decimal Kzkrs { get; set; }
        public string Bstat { get; set; }
        public string Xnetb { get; set; }
        public decimal Frath { get; set; }
        public string Xrueb { get; set; }
        public string Glvor { get; set; }
        public string Grpid { get; set; }
        public string Dokid { get; set; }
        public string Arcid { get; set; }
        public string Iblar { get; set; }
        public string Awtyp { get; set; }
        public string Awkey { get; set; }
        public string Fikrs { get; set; }
        public string Hwaer { get; set; }
        public string Hwae2 { get; set; }
        public string Hwae3 { get; set; }
        public decimal Kurs2 { get; set; }
        public decimal Kurs3 { get; set; }
        public string Basw2 { get; set; }
        public string Basw3 { get; set; }
        public string Umrd2 { get; set; }
        public string Umrd3 { get; set; }
        public string Xstov { get; set; }
        public string Stodt { get; set; }
        public string Xmwst { get; set; }
        public string Curt2 { get; set; }
        public string Curt3 { get; set; }
        public string Kuty2 { get; set; }
        public string Kuty3 { get; set; }
        public string Xsnet { get; set; }
        public string Ausbk { get; set; }
        public string Xusvr { get; set; }
        public string Duefl { get; set; }
        public string Awsys { get; set; }
        public decimal Txkrs { get; set; }
        public decimal Ctxkrs { get; set; }
        public string Lotkz { get; set; }
        public string Xwvof { get; set; }
        public string Stgrd { get; set; }
        public string Ppnam { get; set; }
        public string Brnch { get; set; }
        public string Numpg { get; set; }
        public string Adisc { get; set; }
        public string Xref1Hd { get; set; }
        public string Xref2Hd { get; set; }
        public string Xreversal { get; set; }
        public string Reindat { get; set; }
        public string Rldnr { get; set; }
        public string Ldgrp { get; set; }
        public string Propmano { get; set; }
        public string XblnrAlt { get; set; }
        public string Vatdate { get; set; }
        public string Doccat { get; set; }
        public string Xsplit { get; set; }
        public string CashAlloc { get; set; }
        public string FollowOn { get; set; }
        public string Xreorg { get; set; }
        public string Subset { get; set; }
        public string Kurst { get; set; }
        public decimal Kursx { get; set; }
        public decimal Kur2x { get; set; }
        public decimal Kur3x { get; set; }
        public string Xmca { get; set; }
        public string Resubmission { get; set; }
        public string Sapf15Status { get; set; }
        public string Psoty { get; set; }
        public string Psoak { get; set; }
        public string Psoks { get; set; }
        public string Psosg { get; set; }
        public string Psofn { get; set; }
        public string Intform { get; set; }
        public string Intdate { get; set; }
        public string Psobt { get; set; }
        public string Psozl { get; set; }
        public string Psodt { get; set; }
        public string Psotm { get; set; }
        public string FmUmart { get; set; }
        public string Ccins { get; set; }
        public string Ccnum { get; set; }
        public string Ssblk { get; set; }
        public string Batch { get; set; }
        public string Sname { get; set; }
        public string Sampled { get; set; }
        public string ExcludeFlag { get; set; }
        public string Blind { get; set; }
        public string OffsetStatus { get; set; }
        public string OffsetReferDat { get; set; }
        public string Penrc { get; set; }
        public string Knumv { get; set; }
    }
}
