using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class Bsid
    {
        public string Mandt { get; set; }
        public string Bukrs { get; set; }
        public string Kunnr { get; set; }
        public string Umsks { get; set; }
        public string Umskz { get; set; }
        public string Augdt { get; set; }
        public string Augbl { get; set; }
        public string Zuonr { get; set; }
        public string Gjahr { get; set; }
        public string Belnr { get; set; }
        public string Buzei { get; set; }
        public string Budat { get; set; }
        public string Bldat { get; set; }
        public string Cpudt { get; set; }
        public string Waers { get; set; }
        public string Xblnr { get; set; }
        public string Blart { get; set; }
        public string Monat { get; set; }
        public string Bschl { get; set; }
        public string Zumsk { get; set; }
        public string Shkzg { get; set; }
        public string Gsber { get; set; }
        public string Mwskz { get; set; }
        public decimal Dmbtr { get; set; }
        public decimal Wrbtr { get; set; }
        public decimal Mwsts { get; set; }
        public decimal Wmwst { get; set; }
        public decimal Bdiff { get; set; }
        public decimal Bdif2 { get; set; }
        public string Sgtxt { get; set; }
        public string Projn { get; set; }
        public string Aufnr { get; set; }
        public string Anln1 { get; set; }
        public string Anln2 { get; set; }
        public string Saknr { get; set; }
        public string Hkont { get; set; }
        public string Fkont { get; set; }
        public string Filkd { get; set; }
        public string Zfbdt { get; set; }
        public string Zterm { get; set; }
        public decimal Zbd1t { get; set; }
        public decimal Zbd2t { get; set; }
        public decimal Zbd3t { get; set; }
        public decimal Zbd1p { get; set; }
        public decimal Zbd2p { get; set; }
        public decimal Skfbt { get; set; }
        public decimal Sknto { get; set; }
        public decimal Wskto { get; set; }
        public string Zlsch { get; set; }
        public string Zlspr { get; set; }
        public string Zbfix { get; set; }
        public string Hbkid { get; set; }
        public string Bvtyp { get; set; }
        public string Rebzg { get; set; }
        public string Rebzj { get; set; }
        public string Rebzz { get; set; }
        public string Samnr { get; set; }
        public string Anfbn { get; set; }
        public string Anfbj { get; set; }
        public string Anfbu { get; set; }
        public string Anfae { get; set; }
        public string Mansp { get; set; }
        public string Mschl { get; set; }
        public string Madat { get; set; }
        public string Manst { get; set; }
        public string Maber { get; set; }
        public string Xnetb { get; set; }
        public string Xanet { get; set; }
        public string Xcpdd { get; set; }
        public string Xinve { get; set; }
        public string Xzahl { get; set; }
        public string Mwsk1 { get; set; }
        public decimal Dmbt1 { get; set; }
        public decimal Wrbt1 { get; set; }
        public string Mwsk2 { get; set; }
        public decimal Dmbt2 { get; set; }
        public decimal Wrbt2 { get; set; }
        public string Mwsk3 { get; set; }
        public decimal Dmbt3 { get; set; }
        public decimal Wrbt3 { get; set; }
        public string Bstat { get; set; }
        public string Vbund { get; set; }
        public string Vbeln { get; set; }
        public string Rebzt { get; set; }
        public string Infae { get; set; }
        public string Stceg { get; set; }
        public string Egbld { get; set; }
        public string Eglld { get; set; }
        public string Rstgr { get; set; }
        public string Xnoza { get; set; }
        public string Vertt { get; set; }
        public string Vertn { get; set; }
        public string Vbewa { get; set; }
        public string Wverw { get; set; }
        public string Projk { get; set; }
        public string Fipos { get; set; }
        public string Nplnr { get; set; }
        public string Aufpl { get; set; }
        public string Aplzl { get; set; }
        public string Xegdr { get; set; }
        public decimal Dmbe2 { get; set; }
        public decimal Dmbe3 { get; set; }
        public decimal Dmb21 { get; set; }
        public decimal Dmb22 { get; set; }
        public decimal Dmb23 { get; set; }
        public decimal Dmb31 { get; set; }
        public decimal Dmb32 { get; set; }
        public decimal Dmb33 { get; set; }
        public decimal Bdif3 { get; set; }
        public string Xragl { get; set; }
        public string Uzawe { get; set; }
        public string Xstov { get; set; }
        public decimal Mwst2 { get; set; }
        public decimal Mwst3 { get; set; }
        public decimal Sknt2 { get; set; }
        public decimal Sknt3 { get; set; }
        public string Xref1 { get; set; }
        public string Xref2 { get; set; }
        public string Xarch { get; set; }
        public string Pswsl { get; set; }
        public decimal Pswbt { get; set; }
        public string Lzbkz { get; set; }
        public string Landl { get; set; }
        public string Imkey { get; set; }
        public string Vbel2 { get; set; }
        public string Vpos2 { get; set; }
        public string Posn2 { get; set; }
        public string Eten2 { get; set; }
        public string Fistl { get; set; }
        public string Geber { get; set; }
        public string Dabrz { get; set; }
        public string Xnegp { get; set; }
        public string Kostl { get; set; }
        public string Rfzei { get; set; }
        public string Kkber { get; set; }
        public string Empfb { get; set; }
        public string Prctr { get; set; }
        public string Xref3 { get; set; }
        public string Qsskz { get; set; }
        public string Zinkz { get; set; }
        public string Dtws1 { get; set; }
        public string Dtws2 { get; set; }
        public string Dtws3 { get; set; }
        public string Dtws4 { get; set; }
        public string Xpypr { get; set; }
        public string Kidno { get; set; }
        public decimal Absbt { get; set; }
        public string Ccbtc { get; set; }
        public string Pycur { get; set; }
        public decimal Pyamt { get; set; }
        public string Bupla { get; set; }
        public string Secco { get; set; }
        public string CessionKz { get; set; }
        public decimal Ppdiff { get; set; }
        public decimal Ppdif2 { get; set; }
        public decimal Ppdif3 { get; set; }
        public string Kblnr { get; set; }
        public string Kblpos { get; set; }
        public string GrantNbr { get; set; }
        public string Gmvkz { get; set; }
        public string Srtype { get; set; }
        public string Lotkz { get; set; }
        public string Fkber { get; set; }
        public string Intreno { get; set; }
        public string Pprct { get; set; }
        public string Buzid { get; set; }
        public string Auggj { get; set; }
        public string Hktid { get; set; }
        public string BudgetPd { get; set; }
        public string PaysProv { get; set; }
        public string PaysTran { get; set; }
        public string Mndid { get; set; }
        public string Kontt { get; set; }
        public string Kontl { get; set; }
        public string Uebgdat { get; set; }
        public string Vname { get; set; }
        public string Egrup { get; set; }
        public string Btype { get; set; }
        public string Propmano { get; set; }
    }
}
