using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class Csmy003
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Direccion1 { get; set; }
        public string Direccion2 { get; set; }
        public string CodigoRegion { get; set; }
        public string CodigoEstado { get; set; }
        public string CodigoCiudad { get; set; }
        public string CodigoMcpo { get; set; }
        public string CodigoParroq { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono { get; set; }
        public string Telefono1 { get; set; }
        public string Fax { get; set; }
        public string NoRegTribut { get; set; }
        public string Nit { get; set; }
        public string Grupo { get; set; }
        public string Zona { get; set; }
        public string Asignacion { get; set; }
        public DateTime? FApertura { get; set; }
        public DateTime? FModificacion { get; set; }
        public string FlagModificado { get; set; }
        public string FlagInactivo { get; set; }
        public string TipoNegocio { get; set; }
        public string Segmento { get; set; }
        public string SubSegmentoa { get; set; }
        public string DiaDeCobro { get; set; }
        public string Cobrador { get; set; }
        public string AreaCobranz { get; set; }
        public string RepresLegal { get; set; }
        public string ContNomb1 { get; set; }
        public string ContCarg1 { get; set; }
        public string ContTelf1 { get; set; }
        public string ContEmail1 { get; set; }
        public DateTime? ContFechNacm1 { get; set; }
        public string ContNomb2 { get; set; }
        public string ContCarg2 { get; set; }
        public string ContTelf2 { get; set; }
        public string ContEmail2 { get; set; }
        public DateTime? ContFechNacm2 { get; set; }
        public string ContNomb3 { get; set; }
        public string ContCarg3 { get; set; }
        public string ContTelf3 { get; set; }
        public string ContEmail3 { get; set; }
        public DateTime? ContFechNacm3 { get; set; }
        public string ExentoDeImpuesto { get; set; }
        public string ClienteNuevo { get; set; }
        public string OrdenCompra { get; set; }
        public string OficinaVenta { get; set; }
        public string RutCartero { get; set; }
        public string EMailClient { get; set; }
        public string FlagMat { get; set; }
        public string CodProveedor { get; set; }
        public string Vendedor1 { get; set; }
        public string GiroNegocio { get; set; }
        public string FlagMod03 { get; set; }
        public DateTime? FUltmCompra { get; set; }
        public string Observaciones { get; set; }
        public string FlagNuevo { get; set; }
        public string ClientContado { get; set; }
        public string Categoria { get; set; }
        public decimal? LCredito { get; set; }
        public string CodMcpo { get; set; }
        public int? TImpuesto { get; set; }
        public string CodSubSegmento { get; set; }
        public string ContEspecial { get; set; }
        public decimal? LimiteCredUt { get; set; }
        public string PaginaWeb { get; set; }
        public DateTime? FechaInactivo { get; set; }
        public DateTime? FechaReactivado { get; set; }
        public string FlagCerrado { get; set; }
        public DateTime? FechaCerrado { get; set; }
        public string DepuraCod { get; set; }
        public DateTime? FechaRiesgo { get; set; }
        public string Riesgo { get; set; }
        public DateTime? FechaLegal { get; set; }
        public string Legal { get; set; }
        public DateTime? CierreEjerc { get; set; }
        public decimal? CondPago { get; set; }
        public string Canal { get; set; }
        public string UsuarioMod { get; set; }
        public decimal? CapitalSoc { get; set; }
        public decimal? GrupoCliente { get; set; }
        public double? CodJde { get; set; }
        public decimal? CodigoNumerico { get; set; }
        public string SiDolares { get; set; }
        public string Depurar { get; set; }
        public double? CodJdePadre { get; set; }
        public string FlagAtendido { get; set; }
        public DateTime? FechaAtendido { get; set; }
        public DateTime? FechaDesatendido { get; set; }
        public DateTime? FechaModificadoLimite { get; set; }
        public string NoPasoJde { get; set; }
        public decimal? Saldo { get; set; }
        public string Smacc { get; set; }
        public decimal? IdDireccion { get; set; }
        public string Estado { get; set; }
        public string Municipio { get; set; }
        public string Zzsn01 { get; set; }
        public string Zzsn02 { get; set; }
        public string Zzsn03 { get; set; }
        public string Zzsn04 { get; set; }
        public string Zzsn05 { get; set; }
        public string Zzsn06 { get; set; }
        public string Klabc { get; set; }
    }
}
