using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class Lfa1
    {
        public string Mandt { get; set; }
        public string Lifnr { get; set; }
        public string Land1 { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Name4 { get; set; }
        public string Ort01 { get; set; }
        public string Ort02 { get; set; }
        public string Pfach { get; set; }
        public string Pstl2 { get; set; }
        public string Pstlz { get; set; }
        public string Regio { get; set; }
        public string Sortl { get; set; }
        public string Stras { get; set; }
        public string Adrnr { get; set; }
        public string Mcod1 { get; set; }
        public string Mcod2 { get; set; }
        public string Mcod3 { get; set; }
        public string Anred { get; set; }
        public string Bahns { get; set; }
        public string Bbbnr { get; set; }
        public string Bbsnr { get; set; }
        public string Begru { get; set; }
        public string Brsch { get; set; }
        public string Bubkz { get; set; }
        public string Datlt { get; set; }
        public string Dtams { get; set; }
        public string Dtaws { get; set; }
        public string Erdat { get; set; }
        public string Ernam { get; set; }
        public string Esrnr { get; set; }
        public string Konzs { get; set; }
        public string Ktokk { get; set; }
        public string Kunnr { get; set; }
        public string Lnrza { get; set; }
        public string Loevm { get; set; }
        public string Sperr { get; set; }
        public string Sperm { get; set; }
        public string Spras { get; set; }
        public string Stcd1 { get; set; }
        public string Stcd2 { get; set; }
        public string Stkza { get; set; }
        public string Stkzu { get; set; }
        public string Telbx { get; set; }
        public string Telf1 { get; set; }
        public string Telf2 { get; set; }
        public string Telfx { get; set; }
        public string Teltx { get; set; }
        public string Telx1 { get; set; }
        public string Xcpdk { get; set; }
        public string Xzemp { get; set; }
        public string Vbund { get; set; }
        public string Fiskn { get; set; }
        public string Stceg { get; set; }
        public string Stkzn { get; set; }
        public string Sperq { get; set; }
        public string Gbort { get; set; }
        public string Gbdat { get; set; }
        public string Sexkz { get; set; }
        public string Kraus { get; set; }
        public string Revdb { get; set; }
        public string Qssys { get; set; }
        public string Ktock { get; set; }
        public string Pfort { get; set; }
        public string Werks { get; set; }
        public string Ltsna { get; set; }
        public string Werkr { get; set; }
        public string Plkal { get; set; }
        public string Duefl { get; set; }
        public string Txjcd { get; set; }
        public string Sperz { get; set; }
        public string Scacd { get; set; }
        public string Sfrgr { get; set; }
        public string Lzone { get; set; }
        public string Xlfza { get; set; }
        public string Dlgrp { get; set; }
        public string Fityp { get; set; }
        public string Stcdt { get; set; }
        public string Regss { get; set; }
        public string Actss { get; set; }
        public string Stcd3 { get; set; }
        public string Stcd4 { get; set; }
        public string Stcd5 { get; set; }
        public string Ipisp { get; set; }
        public string Taxbs { get; set; }
        public string Profs { get; set; }
        public string Stgdl { get; set; }
        public string Emnfr { get; set; }
        public string Lfurl { get; set; }
        public string J1kfrepre { get; set; }
        public string J1kftbus { get; set; }
        public string J1kftind { get; set; }
        public string Confs { get; set; }
        public string Updat { get; set; }
        public string Uptim { get; set; }
        public string Nodel { get; set; }
        public string Qssysdat { get; set; }
        public string Podkzb { get; set; }
        public string Fisku { get; set; }
        public string Stenr { get; set; }
        public string CarrierConf { get; set; }
        public string MinComp { get; set; }
        public string TermLi { get; set; }
        public string CrcNum { get; set; }
        public string CvpXblck { get; set; }
        public string Rg { get; set; }
        public string Exp { get; set; }
        public string Uf { get; set; }
        public string Rgdate { get; set; }
        public string Ric { get; set; }
        public string Rne { get; set; }
        public string Rnedate { get; set; }
        public string Cnae { get; set; }
        public string Legalnat { get; set; }
        public string Crtn { get; set; }
        public string Icmstaxpay { get; set; }
        public string Indtyp { get; set; }
        public string Tdt { get; set; }
        public string Comsize { get; set; }
        public string Decregpc { get; set; }
        public decimal JScCapital { get; set; }
        public string JScCurrency { get; set; }
        public string Alc { get; set; }
        public string PmtOffice { get; set; }
        public string Psofg { get; set; }
        public string Psois { get; set; }
        public string Pson1 { get; set; }
        public string Pson2 { get; set; }
        public string Pson3 { get; set; }
        public string Psovn { get; set; }
        public string Psotl { get; set; }
        public string Psohs { get; set; }
        public string Psost { get; set; }
        public string TransportChain { get; set; }
        public decimal StagingTime { get; set; }
        public string SchedulingType { get; set; }
        public string SubmiRelevant { get; set; }
    }
}
