using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class Likp
    {
        public string Mandt { get; set; }
        public string Vbeln { get; set; }
        public string Ernam { get; set; }
        public string Erzet { get; set; }
        public string Erdat { get; set; }
        public string Bzirk { get; set; }
        public string Vstel { get; set; }
        public string Vkorg { get; set; }
        public string Lfart { get; set; }
        public string Autlf { get; set; }
        public string Kzazu { get; set; }
        public string Wadat { get; set; }
        public string Lddat { get; set; }
        public string Tddat { get; set; }
        public string Lfdat { get; set; }
        public string Kodat { get; set; }
        public string Ablad { get; set; }
        public string Inco1 { get; set; }
        public string Inco2 { get; set; }
        public string Expkz { get; set; }
        public string Route { get; set; }
        public string Faksk { get; set; }
        public string Lifsk { get; set; }
        public string Vbtyp { get; set; }
        public string Knfak { get; set; }
        public string Tpqua { get; set; }
        public string Tpgrp { get; set; }
        public string Lprio { get; set; }
        public string Vsbed { get; set; }
        public string Kunnr { get; set; }
        public string Kunag { get; set; }
        public string Kdgrp { get; set; }
        public decimal Stzkl { get; set; }
        public decimal Stzzu { get; set; }
        public decimal Btgew { get; set; }
        public decimal Ntgew { get; set; }
        public string Gewei { get; set; }
        public decimal Volum { get; set; }
        public string Voleh { get; set; }
        public string Anzpk { get; set; }
        public string Berot { get; set; }
        public string Lfuhr { get; set; }
        public string Grulg { get; set; }
        public string Lstel { get; set; }
        public string Tragr { get; set; }
        public string Fkarv { get; set; }
        public string Fkdat { get; set; }
        public string Perfk { get; set; }
        public string Routa { get; set; }
        public string Stafo { get; set; }
        public string Kalsm { get; set; }
        public string Knumv { get; set; }
        public string Waerk { get; set; }
        public string Vkbur { get; set; }
        public decimal Vbeak { get; set; }
        public string Zukrl { get; set; }
        public string Verur { get; set; }
        public string Commn { get; set; }
        public string Stwae { get; set; }
        public decimal Stcur { get; set; }
        public string Exnum { get; set; }
        public string Aenam { get; set; }
        public string Aedat { get; set; }
        public string Lgnum { get; set; }
        public string Lispl { get; set; }
        public string Vkoiv { get; set; }
        public string Vtwiv { get; set; }
        public string Spaiv { get; set; }
        public string Fkaiv { get; set; }
        public string Pioiv { get; set; }
        public string Fkdiv { get; set; }
        public string Kuniv { get; set; }
        public string Kkber { get; set; }
        public string Knkli { get; set; }
        public string Grupp { get; set; }
        public string Sbgrp { get; set; }
        public string Ctlpc { get; set; }
        public string Cmwae { get; set; }
        public decimal Amtbl { get; set; }
        public string Bolnr { get; set; }
        public string Lifnr { get; set; }
        public string Traty { get; set; }
        public string Traid { get; set; }
        public string Cmfre { get; set; }
        public string Cmngv { get; set; }
        public string Xabln { get; set; }
        public string Bldat { get; set; }
        public string WadatIst { get; set; }
        public string Trspg { get; set; }
        public string Tpsid { get; set; }
        public string Lifex { get; set; }
        public string Ternr { get; set; }
        public string KalsmCh { get; set; }
        public string Klief { get; set; }
        public string Kalsp { get; set; }
        public string Knump { get; set; }
        public decimal Netwr { get; set; }
        public string Aulwe { get; set; }
        public string Werks { get; set; }
        public string Lcnum { get; set; }
        public string Abssc { get; set; }
        public string Kouhr { get; set; }
        public string Tduhr { get; set; }
        public string Lduhr { get; set; }
        public string Wauhr { get; set; }
        public string Lgtor { get; set; }
        public string Lgbzo { get; set; }
        public string Akwae { get; set; }
        public decimal Akkur { get; set; }
        public decimal Akprz { get; set; }
        public string Proli { get; set; }
        public string Xblnr { get; set; }
        public string Handle { get; set; }
        public string Tsegfl { get; set; }
        public string Tsegtp { get; set; }
        public string Tzonis { get; set; }
        public string Tzonrc { get; set; }
        public string ContDg { get; set; }
        public string Verursys { get; set; }
        public string Kzwab { get; set; }
        public string Vlstk { get; set; }
        public string Tcode { get; set; }
        public string Vsart { get; set; }
        public string Trmtyp { get; set; }
        public string Sdabw { get; set; }
        public string Vbund { get; set; }
        public string Xwoff { get; set; }
        public string Dirta { get; set; }
        public string Prvbe { get; set; }
        public string Folar { get; set; }
        public string Podat { get; set; }
        public string Potim { get; set; }
        public int Vganz { get; set; }
        public string Imwrk { get; set; }
        public string SpeLoekz { get; set; }
        public string SpeLocSeq { get; set; }
        public string SpeAccAppSts { get; set; }
        public string SpeShpInfSts { get; set; }
        public string SpeRetCanc { get; set; }
        public string SpeWauhrIst { get; set; }
        public string SpeWazoneIst { get; set; }
        public string SpeRevVlstk { get; set; }
        public string SpeLeScenario { get; set; }
        public string SpeOrigSys { get; set; }
        public string SpeChngSys { get; set; }
        public string SpeGeoroute { get; set; }
        public string SpeGeorouteind { get; set; }
        public string SpeCarrierInd { get; set; }
        public string SpeGtsRel { get; set; }
        public string SpeGtsRtCde { get; set; }
        public decimal SpeRelTmstmp { get; set; }
        public string SpeUnitSystem { get; set; }
        public string SpeInvBfrGi { get; set; }
        public string SpeQiStatus { get; set; }
        public string SpeRedInd { get; set; }
        public string Sakes { get; set; }
        public string SpeLifexType { get; set; }
        public string SpeTtype { get; set; }
        public string SpeProNumber { get; set; }
        public byte[] LocGuid { get; set; }
        public string SpeBillingInd { get; set; }
        public string PrinterProfile { get; set; }
        public string MsrActive { get; set; }
        public string Prtnr { get; set; }
        public string StgeLocChange { get; set; }
        public string TmCtrlKey { get; set; }
        public string DlvSplitInitia { get; set; }
        public string DlvVersion { get; set; }
        public string Handoverloc { get; set; }
        public string Handoverdate { get; set; }
        public string Handovertime { get; set; }
        public string Handovertzone { get; set; }
        public string Bev1Luleinh { get; set; }
        public decimal Bev1Rpfaess { get; set; }
        public decimal Bev1Rpkist { get; set; }
        public decimal Bev1Rpcont { get; set; }
        public decimal Bev1Rpsonst { get; set; }
        public string Bev1Rpflgnr { get; set; }
        public string BorgrGrp { get; set; }
        public string Zzidprelista { get; set; }
    }
}
