using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class LipsTemp
    {
        public string Mandt { get; set; }
        public string Vbeln { get; set; }
        public string Posnr { get; set; }
        public string Pstyv { get; set; }
        public string Ernam { get; set; }
        public string Erzet { get; set; }
        public string Erdat { get; set; }
        public string Matnr { get; set; }
        public string Matwa { get; set; }
        public string Matkl { get; set; }
        public string Werks { get; set; }
        public string Lgort { get; set; }
        public string Charg { get; set; }
        public string Lichn { get; set; }
        public string Kdmat { get; set; }
        public string Prodh { get; set; }
        public decimal Lfimg { get; set; }
        public string Meins { get; set; }
        public string Vrkme { get; set; }
        public decimal Umvkz { get; set; }
        public decimal Umvkn { get; set; }
        public decimal Ntgew { get; set; }
        public decimal Brgew { get; set; }
        public string Gewei { get; set; }
        public decimal Volum { get; set; }
        public string Voleh { get; set; }
        public string Kztlf { get; set; }
        public string Uebtk { get; set; }
        public decimal Uebto { get; set; }
        public decimal Untto { get; set; }
        public string Chspl { get; set; }
        public string Faksp { get; set; }
        public string Mbdat { get; set; }
        public decimal Lgmng { get; set; }
        public string Arktx { get; set; }
        public string Lgpbe { get; set; }
        public string Vbelv { get; set; }
        public string Posnv { get; set; }
        public string Vbtyv { get; set; }
        public string Vgsys { get; set; }
        public string Vgbel { get; set; }
        public string Vgpos { get; set; }
        public string Upflu { get; set; }
        public string Uepos { get; set; }
        public string Fkrel { get; set; }
        public string Ladgr { get; set; }
        public string Tragr { get; set; }
        public string Komkz { get; set; }
        public string Lgnum { get; set; }
        public string Lispl { get; set; }
        public string Lgtyp { get; set; }
        public string Lgpla { get; set; }
        public string Bwtex { get; set; }
        public string Bwart { get; set; }
        public string Bwlvs { get; set; }
        public string Kzdlg { get; set; }
        public string Bdart { get; set; }
        public string Plart { get; set; }
        public string Mtart { get; set; }
        public string Xchpf { get; set; }
        public string Xchar { get; set; }
        public string Vgref { get; set; }
        public string Posar { get; set; }
        public string Bwtar { get; set; }
        public string Sumbd { get; set; }
        public string Mtvfp { get; set; }
        public string Eannr { get; set; }
        public string Gsber { get; set; }
        public string Vkbur { get; set; }
        public string Vkgrp { get; set; }
        public string Vtweg { get; set; }
        public string Spart { get; set; }
        public string Grkor { get; set; }
        public string Fmeng { get; set; }
        public decimal Antlf { get; set; }
        public decimal Vbeaf { get; set; }
        public decimal Vbeav { get; set; }
        public string Stafo { get; set; }
        public decimal Wavwr { get; set; }
        public decimal Kzwi1 { get; set; }
        public decimal Kzwi2 { get; set; }
        public decimal Kzwi3 { get; set; }
        public decimal Kzwi4 { get; set; }
        public decimal Kzwi5 { get; set; }
        public decimal Kzwi6 { get; set; }
        public string Sobkz { get; set; }
        public string Aedat { get; set; }
        public string Ean11 { get; set; }
        public string Kvgr1 { get; set; }
        public string Kvgr2 { get; set; }
        public string Kvgr3 { get; set; }
        public string Kvgr4 { get; set; }
        public string Kvgr5 { get; set; }
        public string Mvgr1 { get; set; }
        public string Mvgr2 { get; set; }
        public string Mvgr3 { get; set; }
        public string Mvgr4 { get; set; }
        public string Mvgr5 { get; set; }
        public string Vpzuo { get; set; }
        public string Vgtyp { get; set; }
        public string Rfvgtyp { get; set; }
        public string Kostl { get; set; }
        public string Kokrs { get; set; }
        public string Paobjnr { get; set; }
        public string Prctr { get; set; }
        public string PsPspPnr { get; set; }
        public string Aufnr { get; set; }
        public string PosnrPp { get; set; }
        public string Kdauf { get; set; }
        public string Kdpos { get; set; }
        public string Vpmat { get; set; }
        public string Vpwrk { get; set; }
        public string Prbme { get; set; }
        public double Umref { get; set; }
        public string Knttp { get; set; }
        public string Kzvbr { get; set; }
        public string Fipos { get; set; }
        public string Fistl { get; set; }
        public string Geber { get; set; }
        public string Pckpf { get; set; }
        public string BedarLf { get; set; }
        public string Cmpnt { get; set; }
        public decimal Kcmeng { get; set; }
        public decimal Kcbrgew { get; set; }
        public decimal Kcntgew { get; set; }
        public decimal Kcvolum { get; set; }
        public string Uecha { get; set; }
        public string Cuobj { get; set; }
        public string CuobjCh { get; set; }
        public int Anzsn { get; set; }
        public string Serail { get; set; }
        public string Kcgewei { get; set; }
        public string Kcvoleh { get; set; }
        public string Sernr { get; set; }
        public string Abrli { get; set; }
        public string Abart { get; set; }
        public string Abrvw { get; set; }
        public string Qplos { get; set; }
        public string Qtlos { get; set; }
        public string Nachl { get; set; }
        public string Magrv { get; set; }
        public string Objko { get; set; }
        public string Objpo { get; set; }
        public string Aeskd { get; set; }
        public string Shkzg { get; set; }
        public string Prosa { get; set; }
        public string Uepvw { get; set; }
        public string Empst { get; set; }
        public string Abtnr { get; set; }
        public string Koqui { get; set; }
        public string Stadat { get; set; }
        public string Aktnr { get; set; }
        public string KnumhCh { get; set; }
        public string Prefe { get; set; }
        public string Exart { get; set; }
        public string Clint { get; set; }
        public string Chmvs { get; set; }
        public string Abeln { get; set; }
        public string Abelp { get; set; }
        public double LfimgFlo { get; set; }
        public double LgmngFlo { get; set; }
        public double KcmengFlo { get; set; }
        public string Kzumw { get; set; }
        public decimal Kmpmg { get; set; }
        public string Aurel { get; set; }
        public decimal Kpein { get; set; }
        public string Kmein { get; set; }
        public decimal Netpr { get; set; }
        public decimal Netwr { get; set; }
        public string Kowrr { get; set; }
        public string Kzbew { get; set; }
        public string Mfrgr { get; set; }
        public string Chhpv { get; set; }
        public string Abfor { get; set; }
        public double Abges { get; set; }
        public string Mbuhr { get; set; }
        public string Wktnr { get; set; }
        public string Wktps { get; set; }
        public string J1bcfop { get; set; }
        public string J1btaxlw1 { get; set; }
        public string J1btaxlw2 { get; set; }
        public string J1btxsdc { get; set; }
        public string Situa { get; set; }
        public string Rsnum { get; set; }
        public string Rspos { get; set; }
        public string Rsart { get; set; }
        public string Kannr { get; set; }
        public string Kzfme { get; set; }
        public string Profl { get; set; }
        public decimal Kcmengvme { get; set; }
        public double Kcmengvmef { get; set; }
        public string Kzbws { get; set; }
        public string Pspnr { get; set; }
        public string Eprio { get; set; }
        public string Rules { get; set; }
        public string Kzbef { get; set; }
        public string Mprof { get; set; }
        public string Ematn { get; set; }
        public string Lgbzo { get; set; }
        public string Handle { get; set; }
        public string Verurpos { get; set; }
        public string Lifexpos { get; set; }
        public string Noatp { get; set; }
        public string Nopck { get; set; }
        public string Rblvs { get; set; }
        public string Berid { get; set; }
        public string Bestq { get; set; }
        public string Umbsq { get; set; }
        public string Ummat { get; set; }
        public string Umwrk { get; set; }
        public string Umlgo { get; set; }
        public string Umcha { get; set; }
        public string Umbar { get; set; }
        public string Umsok { get; set; }
        public string Sonum { get; set; }
        public string Usonu { get; set; }
        public decimal Akkur { get; set; }
        public string Akmng { get; set; }
        public string Vkgru { get; set; }
        public string ShkzgUm { get; set; }
        public string Insmk { get; set; }
        public string Kzech { get; set; }
        public string Flgwm { get; set; }
        public string Berkz { get; set; }
        public string Hupos { get; set; }
        public string Nowab { get; set; }
        public string Konto { get; set; }
        public string Kzear { get; set; }
        public string Hsdat { get; set; }
        public string Vfdat { get; set; }
        public string Lfgja { get; set; }
        public string Lfbnr { get; set; }
        public string Lfpos { get; set; }
        public string Grund { get; set; }
        public string Fobwa { get; set; }
        public string Dlvtp { get; set; }
        public decimal Exbwr { get; set; }
        public decimal Bpmng { get; set; }
        public decimal Exvkw { get; set; }
        public double CmpreFlt { get; set; }
        public string Kzpod { get; set; }
        public string Lfdez { get; set; }
        public double Umrev { get; set; }
        public string Podrel { get; set; }
        public string Kzuml { get; set; }
        public string Fkber { get; set; }
        public string GrantNbr { get; set; }
        public string Kzwso { get; set; }
        public string Gmcontrol { get; set; }
        public string PostingChange { get; set; }
        public string UmPsPspPnr { get; set; }
        public string PreVlEtens { get; set; }
        public string SpeGenElikz { get; set; }
        public string SpeScrapInd { get; set; }
        public string SpeAuthNumber { get; set; }
        public byte[] SpeInspoutGuid { get; set; }
        public string SpeFollowUp { get; set; }
        public decimal SpeExpDateExt { get; set; }
        public decimal SpeExpDateInt { get; set; }
        public string SpeAuthComplet { get; set; }
        public decimal Ormng { get; set; }
        public decimal SpeAtpTmstmp { get; set; }
        public string SpeOrigSys { get; set; }
        public decimal SpeLieffz { get; set; }
        public string SpeImwrk { get; set; }
        public string SpeLifexpos2 { get; set; }
        public string SpeExceptCode { get; set; }
        public decimal SpeKeepQty { get; set; }
        public string SpeAlternate { get; set; }
        public string SpeMatSubst { get; set; }
        public string SpeStruc { get; set; }
        public decimal SpeApoQntyfac { get; set; }
        public decimal SpeApoQntydiv { get; set; }
        public string SpeHerkl { get; set; }
        public decimal SpeBxpDateExt { get; set; }
        public string SpeVersion { get; set; }
        public string SpeComplMvt { get; set; }
        public string J1btaxlw4 { get; set; }
        public string J1btaxlw5 { get; set; }
        public string J1btaxlw3 { get; set; }
        public string BudgetPd { get; set; }
        public string Kbnkz { get; set; }
        public string FarrReltype { get; set; }
        public string Sitkz { get; set; }
        public string SgtRcat { get; set; }
        public string SgtScat { get; set; }
        public string ConsOrder { get; set; }
        public string Zzbultos { get; set; }
        public string Zzcontrold { get; set; }
        public string Zzcontrolh { get; set; }
        public string Zzformatod { get; set; }
        public string Zzformatoh { get; set; }
        public string Zzidprelista { get; set; }
        public string Zzidregprelista { get; set; }
        public string Zzorden { get; set; }
        public short Zzcopy { get; set; }
    }
}
