using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class Mara
    {
        public string Mandt { get; set; }
        public string Matnr { get; set; }
        public string Ersda { get; set; }
        public string Ernam { get; set; }
        public string Laeda { get; set; }
        public string Aenam { get; set; }
        public string Vpsta { get; set; }
        public string Pstat { get; set; }
        public string Lvorm { get; set; }
        public string Mtart { get; set; }
        public string Mbrsh { get; set; }
        public string Matkl { get; set; }
        public string Bismt { get; set; }
        public string Meins { get; set; }
        public string Bstme { get; set; }
        public string Zeinr { get; set; }
        public string Zeiar { get; set; }
        public string Zeivr { get; set; }
        public string Zeifo { get; set; }
        public string Aeszn { get; set; }
        public string Blatt { get; set; }
        public string Blanz { get; set; }
        public string Ferth { get; set; }
        public string Formt { get; set; }
        public string Groes { get; set; }
        public string Wrkst { get; set; }
        public string Normt { get; set; }
        public string Labor { get; set; }
        public string Ekwsl { get; set; }
        public decimal Brgew { get; set; }
        public decimal Ntgew { get; set; }
        public string Gewei { get; set; }
        public decimal Volum { get; set; }
        public string Voleh { get; set; }
        public string Behvo { get; set; }
        public string Raube { get; set; }
        public string Tempb { get; set; }
        public string Disst { get; set; }
        public string Tragr { get; set; }
        public string Stoff { get; set; }
        public string Spart { get; set; }
        public string Kunnr { get; set; }
        public string Eannr { get; set; }
        public decimal Wesch { get; set; }
        public string Bwvor { get; set; }
        public string Bwscl { get; set; }
        public string Saiso { get; set; }
        public string Etiar { get; set; }
        public string Etifo { get; set; }
        public string Entar { get; set; }
        public string Ean11 { get; set; }
        public string Numtp { get; set; }
        public decimal Laeng { get; set; }
        public decimal Breit { get; set; }
        public decimal Hoehe { get; set; }
        public string Meabm { get; set; }
        public string Prdha { get; set; }
        public string Aeklk { get; set; }
        public string Cadkz { get; set; }
        public string Qmpur { get; set; }
        public decimal Ergew { get; set; }
        public string Ergei { get; set; }
        public decimal Ervol { get; set; }
        public string Ervoe { get; set; }
        public decimal Gewto { get; set; }
        public decimal Volto { get; set; }
        public string Vabme { get; set; }
        public string Kzrev { get; set; }
        public string Kzkfg { get; set; }
        public string Xchpf { get; set; }
        public string Vhart { get; set; }
        public decimal Fuelg { get; set; }
        public short Stfak { get; set; }
        public string Magrv { get; set; }
        public string Begru { get; set; }
        public string Datab { get; set; }
        public string Liqdt { get; set; }
        public string Saisj { get; set; }
        public string Plgtp { get; set; }
        public string Mlgut { get; set; }
        public string Extwg { get; set; }
        public string Satnr { get; set; }
        public string Attyp { get; set; }
        public string Kzkup { get; set; }
        public string Kznfm { get; set; }
        public string Pmata { get; set; }
        public string Mstae { get; set; }
        public string Mstav { get; set; }
        public string Mstde { get; set; }
        public string Mstdv { get; set; }
        public string Taklv { get; set; }
        public string Rbnrm { get; set; }
        public decimal Mhdrz { get; set; }
        public decimal Mhdhb { get; set; }
        public decimal Mhdlp { get; set; }
        public string Inhme { get; set; }
        public decimal Inhal { get; set; }
        public decimal Vpreh { get; set; }
        public string Etiag { get; set; }
        public decimal Inhbr { get; set; }
        public string Cmeth { get; set; }
        public string Cuobf { get; set; }
        public string Kzumw { get; set; }
        public string Kosch { get; set; }
        public string Sprof { get; set; }
        public string Nrfhg { get; set; }
        public string Mfrpn { get; set; }
        public string Mfrnr { get; set; }
        public string Bmatn { get; set; }
        public string Mprof { get; set; }
        public string Kzwsm { get; set; }
        public string Saity { get; set; }
        public string Profl { get; set; }
        public string Ihivi { get; set; }
        public string Iloos { get; set; }
        public string Serlv { get; set; }
        public string Kzgvh { get; set; }
        public string Xgchp { get; set; }
        public string Kzeff { get; set; }
        public string Compl { get; set; }
        public string Iprkz { get; set; }
        public string Rdmhd { get; set; }
        public string Przus { get; set; }
        public string MtposMara { get; set; }
        public string Bflme { get; set; }
        public string Matfi { get; set; }
        public string Cmrel { get; set; }
        public string Bbtyp { get; set; }
        public string SledBbd { get; set; }
        public string GtinVariant { get; set; }
        public string Gennr { get; set; }
        public string Rmatp { get; set; }
        public string GdsRelevant { get; set; }
        public string Weora { get; set; }
        public string HutypDflt { get; set; }
        public string Pilferable { get; set; }
        public string Whstc { get; set; }
        public string Whmatgr { get; set; }
        public string Hndlcode { get; set; }
        public string Hazmat { get; set; }
        public string Hutyp { get; set; }
        public string TareVar { get; set; }
        public decimal Maxc { get; set; }
        public decimal MaxcTol { get; set; }
        public decimal Maxl { get; set; }
        public decimal Maxb { get; set; }
        public decimal Maxh { get; set; }
        public string MaxdimUom { get; set; }
        public string Herkl { get; set; }
        public string Mfrgr { get; set; }
        public decimal Qqtime { get; set; }
        public string Qqtimeuom { get; set; }
        public string Qgrp { get; set; }
        public string Serial { get; set; }
        public string PsSmartform { get; set; }
        public string Logunit { get; set; }
        public string Cwqrel { get; set; }
        public string Cwqproc { get; set; }
        public string Cwqtolgr { get; set; }
        public string Adprof { get; set; }
        public string Ipmipproduct { get; set; }
        public string AllowPmatIgno { get; set; }
        public string Medium { get; set; }
        public string Commodity { get; set; }
        public string AnimalOrigin { get; set; }
        public string TextileCompInd { get; set; }
        public string SgtCsgr { get; set; }
        public string SgtCovsa { get; set; }
        public string SgtStat { get; set; }
        public string SgtScope { get; set; }
        public string SgtRel { get; set; }
        public string Anp { get; set; }
        public string FshMgAt1 { get; set; }
        public string FshMgAt2 { get; set; }
        public string FshMgAt3 { get; set; }
        public string FshSealv { get; set; }
        public string FshSeaim { get; set; }
        public string FshScMid { get; set; }
        public string PsmCode { get; set; }
        public string Bev1Luleinh { get; set; }
        public string Bev1Luldegrp { get; set; }
        public string Bev1Nestruccat { get; set; }
        public string DsdSlToltyp { get; set; }
        public string DsdSvCntGrp { get; set; }
        public string DsdVcGroup { get; set; }
        public string VsoRTiltInd { get; set; }
        public string VsoRStackInd { get; set; }
        public string VsoRBotInd { get; set; }
        public string VsoRTopInd { get; set; }
        public string VsoRStackNo { get; set; }
        public string VsoRPalInd { get; set; }
        public decimal VsoRPalOvrD { get; set; }
        public decimal VsoRPalOvrW { get; set; }
        public decimal VsoRPalBHt { get; set; }
        public decimal VsoRPalMinH { get; set; }
        public decimal VsoRTolBHt { get; set; }
        public string VsoRNoPGvh { get; set; }
        public string VsoRQuanUnit { get; set; }
        public string VsoRKzgvhInd { get; set; }
        public string Packcode { get; set; }
        public string DgPackStatus { get; set; }
        public string Mcond { get; set; }
        public string Retdelc { get; set; }
        public string LoglevReto { get; set; }
        public string Nsnid { get; set; }
        public string Imatn { get; set; }
        public string Picnum { get; set; }
        public string Bstat { get; set; }
        public string ColorAtinn { get; set; }
        public string Size1Atinn { get; set; }
        public string Size2Atinn { get; set; }
        public string Color { get; set; }
        public string Size1 { get; set; }
        public string Size2 { get; set; }
        public string FreeChar { get; set; }
        public string CareCode { get; set; }
        public string BrandId { get; set; }
        public string FiberCode1 { get; set; }
        public string FiberPart1 { get; set; }
        public string FiberCode2 { get; set; }
        public string FiberPart2 { get; set; }
        public string FiberCode3 { get; set; }
        public string FiberPart3 { get; set; }
        public string FiberCode4 { get; set; }
        public string FiberPart4 { get; set; }
        public string FiberCode5 { get; set; }
        public string FiberPart5 { get; set; }
        public string Fashgrd { get; set; }
    }
}
