using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class Mbew
    {
        public string Mandt { get; set; }
        public string Matnr { get; set; }
        public string Bwkey { get; set; }
        public string Bwtar { get; set; }
        public string Lvorm { get; set; }
        public decimal Lbkum { get; set; }
        public decimal Salk3 { get; set; }
        public string Vprsv { get; set; }
        public decimal Verpr { get; set; }
        public decimal Stprs { get; set; }
        public decimal Peinh { get; set; }
        public string Bklas { get; set; }
        public decimal Salkv { get; set; }
        public decimal Vmkum { get; set; }
        public decimal Vmsal { get; set; }
        public string Vmvpr { get; set; }
        public decimal Vmver { get; set; }
        public decimal Vmstp { get; set; }
        public decimal Vmpei { get; set; }
        public string Vmbkl { get; set; }
        public decimal Vmsav { get; set; }
        public decimal Vjkum { get; set; }
        public decimal Vjsal { get; set; }
        public string Vjvpr { get; set; }
        public decimal Vjver { get; set; }
        public decimal Vjstp { get; set; }
        public decimal Vjpei { get; set; }
        public string Vjbkl { get; set; }
        public decimal Vjsav { get; set; }
        public string Lfgja { get; set; }
        public string Lfmon { get; set; }
        public string Bwtty { get; set; }
        public decimal Stprv { get; set; }
        public string Laepr { get; set; }
        public decimal Zkprs { get; set; }
        public string Zkdat { get; set; }
        public decimal Timestamp { get; set; }
        public decimal Bwprs { get; set; }
        public decimal Bwprh { get; set; }
        public decimal Vjbws { get; set; }
        public decimal Vjbwh { get; set; }
        public decimal Vvjsl { get; set; }
        public decimal Vvjlb { get; set; }
        public decimal Vvmlb { get; set; }
        public decimal Vvsal { get; set; }
        public decimal Zplpr { get; set; }
        public decimal Zplp1 { get; set; }
        public decimal Zplp2 { get; set; }
        public decimal Zplp3 { get; set; }
        public string Zpld1 { get; set; }
        public string Zpld2 { get; set; }
        public string Zpld3 { get; set; }
        public string Pperz { get; set; }
        public string Pperl { get; set; }
        public string Pperv { get; set; }
        public string Kalkz { get; set; }
        public string Kalkl { get; set; }
        public string Kalkv { get; set; }
        public string Kalsc { get; set; }
        public string Xlifo { get; set; }
        public string Mypol { get; set; }
        public decimal Bwph1 { get; set; }
        public decimal Bwps1 { get; set; }
        public string Abwkz { get; set; }
        public string Pstat { get; set; }
        public string Kaln1 { get; set; }
        public string Kalnr { get; set; }
        public string Bwva1 { get; set; }
        public string Bwva2 { get; set; }
        public string Bwva3 { get; set; }
        public string Vers1 { get; set; }
        public string Vers2 { get; set; }
        public string Vers3 { get; set; }
        public string Hrkft { get; set; }
        public string Kosgr { get; set; }
        public string Pprdz { get; set; }
        public string Pprdl { get; set; }
        public string Pprdv { get; set; }
        public string Pdatz { get; set; }
        public string Pdatl { get; set; }
        public string Pdatv { get; set; }
        public string Ekalr { get; set; }
        public decimal Vplpr { get; set; }
        public string Mlmaa { get; set; }
        public string Mlast { get; set; }
        public decimal Lplpr { get; set; }
        public decimal Vksal { get; set; }
        public string Hkmat { get; set; }
        public string Sperw { get; set; }
        public string Kziwl { get; set; }
        public string Wlinl { get; set; }
        public string Abciw { get; set; }
        public decimal Bwspa { get; set; }
        public decimal Lplpx { get; set; }
        public decimal Vplpx { get; set; }
        public decimal Fplpx { get; set; }
        public string Lbwst { get; set; }
        public string Vbwst { get; set; }
        public string Fbwst { get; set; }
        public string Eklas { get; set; }
        public string Qklas { get; set; }
        public string Mtuse { get; set; }
        public string Mtorg { get; set; }
        public string Ownpr { get; set; }
        public string Xbewm { get; set; }
        public decimal Bwpei { get; set; }
        public string Mbrue { get; set; }
        public string Oklas { get; set; }
        public string Oippinv { get; set; }
    }
}
