using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class Mseg
    {
        public string Mandt { get; set; }
        public string Mblnr { get; set; }
        public string Mjahr { get; set; }
        public string Zeile { get; set; }
        public string LineId { get; set; }
        public string ParentId { get; set; }
        public string LineDepth { get; set; }
        public string MaaUrzei { get; set; }
        public string Bwart { get; set; }
        public string Xauto { get; set; }
        public string Matnr { get; set; }
        public string Werks { get; set; }
        public string Lgort { get; set; }
        public string Charg { get; set; }
        public string Insmk { get; set; }
        public string Zusch { get; set; }
        public string Zustd { get; set; }
        public string Sobkz { get; set; }
        public string Lifnr { get; set; }
        public string Kunnr { get; set; }
        public string Kdauf { get; set; }
        public string Kdpos { get; set; }
        public string Kdein { get; set; }
        public string Plpla { get; set; }
        public string Shkzg { get; set; }
        public string Waers { get; set; }
        public decimal Dmbtr { get; set; }
        public decimal Bnbtr { get; set; }
        public decimal Bualt { get; set; }
        public string Shkum { get; set; }
        public decimal Dmbum { get; set; }
        public string Bwtar { get; set; }
        public decimal Menge { get; set; }
        public string Meins { get; set; }
        public decimal Erfmg { get; set; }
        public string Erfme { get; set; }
        public decimal Bpmng { get; set; }
        public string Bprme { get; set; }
        public string Ebeln { get; set; }
        public string Ebelp { get; set; }
        public string Lfbja { get; set; }
        public string Lfbnr { get; set; }
        public string Lfpos { get; set; }
        public string Sjahr { get; set; }
        public string Smbln { get; set; }
        public string Smblp { get; set; }
        public string Elikz { get; set; }
        public string Sgtxt { get; set; }
        public string Equnr { get; set; }
        public string Wempf { get; set; }
        public string Ablad { get; set; }
        public string Gsber { get; set; }
        public string Kokrs { get; set; }
        public string Pargb { get; set; }
        public string Parbu { get; set; }
        public string Kostl { get; set; }
        public string Projn { get; set; }
        public string Aufnr { get; set; }
        public string Anln1 { get; set; }
        public string Anln2 { get; set; }
        public string Xskst { get; set; }
        public string Xsauf { get; set; }
        public string Xspro { get; set; }
        public string Xserg { get; set; }
        public string Gjahr { get; set; }
        public string Xruem { get; set; }
        public string Xruej { get; set; }
        public string Bukrs { get; set; }
        public string Belnr { get; set; }
        public string Buzei { get; set; }
        public string Belum { get; set; }
        public string Buzum { get; set; }
        public string Rsnum { get; set; }
        public string Rspos { get; set; }
        public string Kzear { get; set; }
        public decimal Pbamg { get; set; }
        public string Kzstr { get; set; }
        public string Ummat { get; set; }
        public string Umwrk { get; set; }
        public string Umlgo { get; set; }
        public string Umcha { get; set; }
        public string Umzst { get; set; }
        public string Umzus { get; set; }
        public string Umbar { get; set; }
        public string Umsok { get; set; }
        public string Kzbew { get; set; }
        public string Kzvbr { get; set; }
        public string Kzzug { get; set; }
        public string Weunb { get; set; }
        public decimal Palan { get; set; }
        public string Lgnum { get; set; }
        public string Lgtyp { get; set; }
        public string Lgpla { get; set; }
        public string Bestq { get; set; }
        public string Bwlvs { get; set; }
        public string Tbnum { get; set; }
        public string Tbpos { get; set; }
        public string Xblvs { get; set; }
        public string Vschn { get; set; }
        public string Nschn { get; set; }
        public string Dypla { get; set; }
        public string Ubnum { get; set; }
        public string Tbpri { get; set; }
        public string Tanum { get; set; }
        public string Weanz { get; set; }
        public string Grund { get; set; }
        public string Evers { get; set; }
        public string Evere { get; set; }
        public string Imkey { get; set; }
        public string Kstrg { get; set; }
        public string Paobjnr { get; set; }
        public string Prctr { get; set; }
        public string PsPspPnr { get; set; }
        public string Nplnr { get; set; }
        public string Aufpl { get; set; }
        public string Aplzl { get; set; }
        public string Aufps { get; set; }
        public string Vptnr { get; set; }
        public string Fipos { get; set; }
        public string Sakto { get; set; }
        public decimal Bstmg { get; set; }
        public string Bstme { get; set; }
        public string Xwsbr { get; set; }
        public string Emlif { get; set; }
        public decimal Exbwr { get; set; }
        public decimal Vkwrt { get; set; }
        public string Aktnr { get; set; }
        public string Zekkn { get; set; }
        public string Vfdat { get; set; }
        public string CuobjCh { get; set; }
        public decimal Exvkw { get; set; }
        public string Pprctr { get; set; }
        public string Rsart { get; set; }
        public string Geber { get; set; }
        public string Fistl { get; set; }
        public string Matbf { get; set; }
        public string Ummab { get; set; }
        public string Bustm { get; set; }
        public string Bustw { get; set; }
        public string Mengu { get; set; }
        public string Wertu { get; set; }
        public decimal Lbkum { get; set; }
        public decimal Salk3 { get; set; }
        public string Vprsv { get; set; }
        public string Fkber { get; set; }
        public string Dabrbz { get; set; }
        public decimal Vkwra { get; set; }
        public string Dabrz { get; set; }
        public string Xbeau { get; set; }
        public decimal Lsmng { get; set; }
        public string Lsmeh { get; set; }
        public string Kzbws { get; set; }
        public string Qinspst { get; set; }
        public string Urzei { get; set; }
        public decimal J1bexbase { get; set; }
        public string Mwskz { get; set; }
        public string Txjcd { get; set; }
        public string Ematn { get; set; }
        public string J1agirupd { get; set; }
        public string Vkmws { get; set; }
        public string Hsdat { get; set; }
        public string Berkz { get; set; }
        public string MatKdauf { get; set; }
        public string MatKdpos { get; set; }
        public string MatPspnr { get; set; }
        public string Xwoff { get; set; }
        public string Bemot { get; set; }
        public string Prznr { get; set; }
        public string Llief { get; set; }
        public string Lstar { get; set; }
        public string Xobew { get; set; }
        public string GrantNbr { get; set; }
        public string ZustdT156m { get; set; }
        public string SpeGtsStockTy { get; set; }
        public string Kblnr { get; set; }
        public string Kblpos { get; set; }
        public string Xmacc { get; set; }
        public string VgartMkpf { get; set; }
        public string BudatMkpf { get; set; }
        public string CpudtMkpf { get; set; }
        public string CputmMkpf { get; set; }
        public string UsnamMkpf { get; set; }
        public string XblnrMkpf { get; set; }
        public string Tcode2Mkpf { get; set; }
        public string VbelnIm { get; set; }
        public string VbelpIm { get; set; }
        public string SgtScat { get; set; }
        public string SgtUmscat { get; set; }
        public string Dataaging { get; set; }
        public string SgtRcat { get; set; }
        public string Bev2EdKzVer { get; set; }
        public string Bev2EdUser { get; set; }
        public string Bev2EdAedat { get; set; }
        public string Bev2EdAetim { get; set; }
        public decimal Oinavnw { get; set; }
        public string Oicondcod { get; set; }
        public string Condi { get; set; }
    }
}
