using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class VbakTemp
    {
        public string Mandt { get; set; }
        public string Vbeln { get; set; }
        public string Erdat { get; set; }
        public string Erzet { get; set; }
        public string Ernam { get; set; }
        public string Angdt { get; set; }
        public string Bnddt { get; set; }
        public string Audat { get; set; }
        public string Vbtyp { get; set; }
        public string Trvog { get; set; }
        public string Auart { get; set; }
        public string Augru { get; set; }
        public string Gwldt { get; set; }
        public string Submi { get; set; }
        public string Lifsk { get; set; }
        public string Faksk { get; set; }
        public decimal Netwr { get; set; }
        public string Waerk { get; set; }
        public string Vkorg { get; set; }
        public string Vtweg { get; set; }
        public string Spart { get; set; }
        public string Vkgrp { get; set; }
        public string Vkbur { get; set; }
        public string Gsber { get; set; }
        public string Gskst { get; set; }
        public string Guebg { get; set; }
        public string Gueen { get; set; }
        public string Knumv { get; set; }
        public string Vdatu { get; set; }
        public string Vprgr { get; set; }
        public string Autlf { get; set; }
        public string Vbkla { get; set; }
        public string Vbklt { get; set; }
        public string Kalsm { get; set; }
        public string Vsbed { get; set; }
        public string Fkara { get; set; }
        public string Awahr { get; set; }
        public string Ktext { get; set; }
        public string Bstnk { get; set; }
        public string Bsark { get; set; }
        public string Bstdk { get; set; }
        public string Bstzd { get; set; }
        public string Ihrez { get; set; }
        public string Bname { get; set; }
        public string Telf1 { get; set; }
        public decimal Mahza { get; set; }
        public string Mahdt { get; set; }
        public string Kunnr { get; set; }
        public string Kostl { get; set; }
        public string Stafo { get; set; }
        public string Stwae { get; set; }
        public string Aedat { get; set; }
        public string Kvgr1 { get; set; }
        public string Kvgr2 { get; set; }
        public string Kvgr3 { get; set; }
        public string Kvgr4 { get; set; }
        public string Kvgr5 { get; set; }
        public string Knuma { get; set; }
        public string Kokrs { get; set; }
        public string PsPspPnr { get; set; }
        public string Kurst { get; set; }
        public string Kkber { get; set; }
        public string Knkli { get; set; }
        public string Grupp { get; set; }
        public string Sbgrp { get; set; }
        public string Ctlpc { get; set; }
        public string Cmwae { get; set; }
        public string Cmfre { get; set; }
        public string Cmnup { get; set; }
        public string Cmngv { get; set; }
        public decimal Amtbl { get; set; }
        public string HitypPr { get; set; }
        public string Abrvw { get; set; }
        public string Abdis { get; set; }
        public string Vgbel { get; set; }
        public string Objnr { get; set; }
        public string BukrsVf { get; set; }
        public string Taxk1 { get; set; }
        public string Taxk2 { get; set; }
        public string Taxk3 { get; set; }
        public string Taxk4 { get; set; }
        public string Taxk5 { get; set; }
        public string Taxk6 { get; set; }
        public string Taxk7 { get; set; }
        public string Taxk8 { get; set; }
        public string Taxk9 { get; set; }
        public string Xblnr { get; set; }
        public string Zuonr { get; set; }
        public string Vgtyp { get; set; }
        public string KalsmCh { get; set; }
        public string Agrzr { get; set; }
        public string Aufnr { get; set; }
        public string Qmnum { get; set; }
        public string VbelnGrp { get; set; }
        public string SchemeGrp { get; set; }
        public string AbrufPart { get; set; }
        public string Abhod { get; set; }
        public string Abhov { get; set; }
        public string Abhob { get; set; }
        public string Rplnr { get; set; }
        public string Vzeit { get; set; }
        public string StcegL { get; set; }
        public string Landtx { get; set; }
        public string Xegdr { get; set; }
        public string EnqueueGrp { get; set; }
        public string DatFzau { get; set; }
        public string Fmbdat { get; set; }
        public string VsnmrV { get; set; }
        public string Handle { get; set; }
        public string Proli { get; set; }
        public string ContDg { get; set; }
        public string CrmGuid { get; set; }
        public decimal UpdTmstmp { get; set; }
        public string MsrId { get; set; }
        public string TmCtrlKey { get; set; }
        public string Handoverloc { get; set; }
        public string PsmBudat { get; set; }
        public string Swenr { get; set; }
        public string Smenr { get; set; }
        public string Phase { get; set; }
        public string Mtlaur { get; set; }
        public int Stage { get; set; }
        public string HbContReason { get; set; }
        public string HbExpdate { get; set; }
        public string HbResdate { get; set; }
        public string Logsysb { get; set; }
        public string Kalcd { get; set; }
        public string Multi { get; set; }
        public string Sppaym { get; set; }
        public string Zzidprelista { get; set; }
    }
}
