using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class VbapTemp
    {
        public string Mandt { get; set; }
        public string Vbeln { get; set; }
        public string Posnr { get; set; }
        public string Matnr { get; set; }
        public string Matwa { get; set; }
        public string Pmatn { get; set; }
        public string Charg { get; set; }
        public string Matkl { get; set; }
        public string Arktx { get; set; }
        public string Pstyv { get; set; }
        public string Posar { get; set; }
        public string Lfrel { get; set; }
        public string Fkrel { get; set; }
        public string Uepos { get; set; }
        public string Grpos { get; set; }
        public string Abgru { get; set; }
        public string Prodh { get; set; }
        public decimal Zwert { get; set; }
        public decimal Zmeng { get; set; }
        public string Zieme { get; set; }
        public decimal Umziz { get; set; }
        public decimal Umzin { get; set; }
        public string Meins { get; set; }
        public decimal Smeng { get; set; }
        public decimal Ablfz { get; set; }
        public string Abdat { get; set; }
        public decimal Absfz { get; set; }
        public string Posex { get; set; }
        public string Kdmat { get; set; }
        public decimal Kbver { get; set; }
        public decimal Kever { get; set; }
        public string Vkgru { get; set; }
        public string Vkaus { get; set; }
        public string Grkor { get; set; }
        public string Fmeng { get; set; }
        public string Uebtk { get; set; }
        public decimal Uebto { get; set; }
        public decimal Untto { get; set; }
        public string Faksp { get; set; }
        public string Atpkz { get; set; }
        public string Rkfkf { get; set; }
        public string Spart { get; set; }
        public string Gsber { get; set; }
        public decimal Netwr { get; set; }
        public string Waerk { get; set; }
        public decimal Antlf { get; set; }
        public string Kztlf { get; set; }
        public string Chspl { get; set; }
        public decimal Kwmeng { get; set; }
        public decimal Lsmeng { get; set; }
        public decimal Kbmeng { get; set; }
        public decimal Klmeng { get; set; }
        public string Vrkme { get; set; }
        public decimal Umvkz { get; set; }
        public decimal Umvkn { get; set; }
        public decimal Brgew { get; set; }
        public decimal Ntgew { get; set; }
        public string Gewei { get; set; }
        public decimal Volum { get; set; }
        public string Voleh { get; set; }
        public string Vbelv { get; set; }
        public string Posnv { get; set; }
        public string Vgbel { get; set; }
        public string Vgpos { get; set; }
        public string Voref { get; set; }
        public string Upflu { get; set; }
        public string Erlre { get; set; }
        public string Lprio { get; set; }
        public string Werks { get; set; }
        public string Lgort { get; set; }
        public string Vstel { get; set; }
        public string Route { get; set; }
        public string Stkey { get; set; }
        public string Stdat { get; set; }
        public string Stlnr { get; set; }
        public decimal Stpos { get; set; }
        public string Awahr { get; set; }
        public string Erdat { get; set; }
        public string Ernam { get; set; }
        public string Erzet { get; set; }
        public string Taxm1 { get; set; }
        public string Taxm2 { get; set; }
        public string Taxm3 { get; set; }
        public string Taxm4 { get; set; }
        public string Taxm5 { get; set; }
        public string Taxm6 { get; set; }
        public string Taxm7 { get; set; }
        public string Taxm8 { get; set; }
        public string Taxm9 { get; set; }
        public decimal Vbeaf { get; set; }
        public decimal Vbeav { get; set; }
        public string Vgref { get; set; }
        public decimal Netpr { get; set; }
        public decimal Kpein { get; set; }
        public string Kmein { get; set; }
        public string Shkzg { get; set; }
        public string Sktof { get; set; }
        public string Mtvfp { get; set; }
        public string Sumbd { get; set; }
        public string Kondm { get; set; }
        public string Ktgrm { get; set; }
        public string Bonus { get; set; }
        public string Provg { get; set; }
        public string Eannr { get; set; }
        public string Prsok { get; set; }
        public string Bwtar { get; set; }
        public string Bwtex { get; set; }
        public string Xchpf { get; set; }
        public string Xchar { get; set; }
        public decimal Lfmng { get; set; }
        public string Stafo { get; set; }
        public decimal Wavwr { get; set; }
        public decimal Kzwi1 { get; set; }
        public decimal Kzwi2 { get; set; }
        public decimal Kzwi3 { get; set; }
        public decimal Kzwi4 { get; set; }
        public decimal Kzwi5 { get; set; }
        public decimal Kzwi6 { get; set; }
        public decimal Stcur { get; set; }
        public string Aedat { get; set; }
        public string Ean11 { get; set; }
        public string Fixmg { get; set; }
        public string Prctr { get; set; }
        public string Mvgr1 { get; set; }
        public string Mvgr2 { get; set; }
        public string Mvgr3 { get; set; }
        public string Mvgr4 { get; set; }
        public string Mvgr5 { get; set; }
        public decimal Kmpmg { get; set; }
        public string Sugrd { get; set; }
        public string Sobkz { get; set; }
        public string Vpzuo { get; set; }
        public string Paobjnr { get; set; }
        public string PsPspPnr { get; set; }
        public string Aufnr { get; set; }
        public string Vpmat { get; set; }
        public string Vpwrk { get; set; }
        public string Prbme { get; set; }
        public double Umref { get; set; }
        public string Knttp { get; set; }
        public string Kzvbr { get; set; }
        public string Sernr { get; set; }
        public string Objnr { get; set; }
        public string Abgrs { get; set; }
        public string Bedae { get; set; }
        public decimal Cmpre { get; set; }
        public string Cmtfg { get; set; }
        public string Cmpnt { get; set; }
        public decimal Cmkua { get; set; }
        public string Cuobj { get; set; }
        public string CuobjCh { get; set; }
        public string Cepok { get; set; }
        public string Koupd { get; set; }
        public string Serail { get; set; }
        public int Anzsn { get; set; }
        public string Nachl { get; set; }
        public string Magrv { get; set; }
        public string Mprok { get; set; }
        public string Vgtyp { get; set; }
        public string Prosa { get; set; }
        public string Uepvw { get; set; }
        public string Kalnr { get; set; }
        public string Klvar { get; set; }
        public string Sposn { get; set; }
        public string Kowrr { get; set; }
        public string Stadat { get; set; }
        public string Exart { get; set; }
        public string Prefe { get; set; }
        public string Knumh { get; set; }
        public string Clint { get; set; }
        public string Chmvs { get; set; }
        public string Stlty { get; set; }
        public string Stlkn { get; set; }
        public string Stpoz { get; set; }
        public string Stman { get; set; }
        public string ZschlK { get; set; }
        public string KalsmK { get; set; }
        public string Kalvar { get; set; }
        public string Kosch { get; set; }
        public string Upmat { get; set; }
        public string Ukonm { get; set; }
        public string Mfrgr { get; set; }
        public string Plavo { get; set; }
        public string Kannr { get; set; }
        public double CmpreFlt { get; set; }
        public string Abfor { get; set; }
        public double Abges { get; set; }
        public string J1bcfop { get; set; }
        public string J1btaxlw1 { get; set; }
        public string J1btaxlw2 { get; set; }
        public string J1btxsdc { get; set; }
        public string Wktnr { get; set; }
        public string Wktps { get; set; }
        public string Skopf { get; set; }
        public string Kzbws { get; set; }
        public string Wgru1 { get; set; }
        public string Wgru2 { get; set; }
        public string KnumaPi { get; set; }
        public string KnumaAg { get; set; }
        public string Kzfme { get; set; }
        public string Lstanr { get; set; }
        public string Techs { get; set; }
        public decimal Mwsbp { get; set; }
        public string Berid { get; set; }
        public string Pctrf { get; set; }
        public string LogsysExt { get; set; }
        public string J1btaxlw3 { get; set; }
        public string J1btaxlw4 { get; set; }
        public string J1btaxlw5 { get; set; }
        public string Stockloc { get; set; }
        public string Sloctype { get; set; }
        public string MsrRetReason { get; set; }
        public string MsrRefundCode { get; set; }
        public string MsrApprovBlock { get; set; }
        public string NrabKnumh { get; set; }
        public string TrmriskRelevant { get; set; }
        public string SgtRcat { get; set; }
        public string Handoverloc { get; set; }
        public string Handoverdate { get; set; }
        public string Handovertime { get; set; }
        public string TcAutDet { get; set; }
        public string ManualTcReason { get; set; }
        public string FiscalIncentive { get; set; }
        public string TaxSubjectSt { get; set; }
        public string FiscalIncentiveId { get; set; }
        public string Spcsto { get; set; }
        public string RevaccRefid { get; set; }
        public string RevaccReftype { get; set; }
        public string Bev1Srfund { get; set; }
        public string AufplOlc { get; set; }
        public string AplzlOlc { get; set; }
        public string FercInd { get; set; }
        public string Kostl { get; set; }
        public string Fonds { get; set; }
        public string Fistl { get; set; }
        public string Fkber { get; set; }
        public string GrantNbr { get; set; }
        public string IuidRelevant { get; set; }
        public string PrsObjnr { get; set; }
        public string PrsSdSpsnr { get; set; }
        public string PrsWorkPeriod { get; set; }
        public string Pargb { get; set; }
        public string AufplOaa { get; set; }
        public string AplzlOaa { get; set; }
        public string Zzcontrold { get; set; }
        public string Zzcontrolh { get; set; }
        public string Zzformatod { get; set; }
        public string Zzformatoh { get; set; }
        public string Zzbulto { get; set; }
        public string Zzidprelista { get; set; }
        public string Zzidregprelista { get; set; }
        public string Zzorden { get; set; }
        public short Zzcopy { get; set; }
    }
}
