using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class VbkdTemp
    {
        public string Mandt { get; set; }
        public string Vbeln { get; set; }
        public string Posnr { get; set; }
        public string Konda { get; set; }
        public string Kdgrp { get; set; }
        public string Bzirk { get; set; }
        public string Pltyp { get; set; }
        public string Inco1 { get; set; }
        public string Inco2 { get; set; }
        public string Kzazu { get; set; }
        public string Perfk { get; set; }
        public string Perrl { get; set; }
        public string Mrnkz { get; set; }
        public decimal Kurrf { get; set; }
        public string Valtg { get; set; }
        public string Valdt { get; set; }
        public string Zterm { get; set; }
        public string Zlsch { get; set; }
        public string Ktgrd { get; set; }
        public decimal Kursk { get; set; }
        public string Prsdt { get; set; }
        public string Fkdat { get; set; }
        public string Fbuda { get; set; }
        public string Gjahr { get; set; }
        public string Poper { get; set; }
        public decimal Stcur { get; set; }
        public string Mschl { get; set; }
        public string Mansp { get; set; }
        public string Fplnr { get; set; }
        public string Waktion { get; set; }
        public string Abssc { get; set; }
        public string Lcnum { get; set; }
        public string J1afitp { get; set; }
        public string J1arfz { get; set; }
        public string J1aregio { get; set; }
        public string J1agicd { get; set; }
        public string J1adtyp { get; set; }
        public string J1atxrel { get; set; }
        public string Abtnr { get; set; }
        public string Empst { get; set; }
        public string Bstkd { get; set; }
        public string Bstdk { get; set; }
        public string Bsark { get; set; }
        public string Ihrez { get; set; }
        public string BstkdE { get; set; }
        public string BstdkE { get; set; }
        public string BsarkE { get; set; }
        public string IhrezE { get; set; }
        public string PosexE { get; set; }
        public string KurskDat { get; set; }
        public string KurrfDat { get; set; }
        public string Kdkg1 { get; set; }
        public string Kdkg2 { get; set; }
        public string Kdkg3 { get; set; }
        public string Kdkg4 { get; set; }
        public string Kdkg5 { get; set; }
        public string Wkwae { get; set; }
        public decimal Wkkur { get; set; }
        public string Akwae { get; set; }
        public decimal Akkur { get; set; }
        public decimal Akprz { get; set; }
        public string J1aindxp { get; set; }
        public string J1aidatep { get; set; }
        public string BstkdM { get; set; }
        public string Delco { get; set; }
        public string Ffprf { get; set; }
        public string Bemot { get; set; }
        public string Faktf { get; set; }
        public string Rrrel { get; set; }
        public string Acdatv { get; set; }
        public string Vsart { get; set; }
        public string Traty { get; set; }
        public string Trmtyp { get; set; }
        public string Sdabw { get; set; }
        public string Wminr { get; set; }
        public string Fkber { get; set; }
        public string Podkz { get; set; }
        public byte[] Campaign { get; set; }
        public string Vkont { get; set; }
        public string DpbpRefFplnr { get; set; }
        public string DpbpRefFpltr { get; set; }
        public string Revsp { get; set; }
        public string Revevtyp { get; set; }
        public string FarrReltype { get; set; }
        public string Vtref { get; set; }
        public string J1tpbupl { get; set; }
        public string PeropBeg { get; set; }
        public string PeropEnd { get; set; }
        public string Stcode { get; set; }
        public string Formc1 { get; set; }
        public string Formc2 { get; set; }
        public string Steuc { get; set; }
        public string Compreas { get; set; }
        public string Mndid { get; set; }
        public string PayType { get; set; }
        public string Sepon { get; set; }
        public string Mndvg { get; set; }
    }
}
