using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class Vbrk
    {
        public string Mandt { get; set; }
        public string Vbeln { get; set; }
        public string Fkart { get; set; }
        public string Fktyp { get; set; }
        public string Vbtyp { get; set; }
        public string Waerk { get; set; }
        public string Vkorg { get; set; }
        public string Vtweg { get; set; }
        public string Kalsm { get; set; }
        public string Knumv { get; set; }
        public string Vsbed { get; set; }
        public string Fkdat { get; set; }
        public string Belnr { get; set; }
        public string Gjahr { get; set; }
        public string Poper { get; set; }
        public string Konda { get; set; }
        public string Kdgrp { get; set; }
        public string Bzirk { get; set; }
        public string Pltyp { get; set; }
        public string Inco1 { get; set; }
        public string Inco2 { get; set; }
        public string Expkz { get; set; }
        public string Rfbsk { get; set; }
        public string Mrnkz { get; set; }
        public decimal Kurrf { get; set; }
        public string Cpkur { get; set; }
        public string Valtg { get; set; }
        public string Valdt { get; set; }
        public string Zterm { get; set; }
        public string Zlsch { get; set; }
        public string Ktgrd { get; set; }
        public string Land1 { get; set; }
        public string Regio { get; set; }
        public string Counc { get; set; }
        public string Cityc { get; set; }
        public string Bukrs { get; set; }
        public string Taxk1 { get; set; }
        public string Taxk2 { get; set; }
        public string Taxk3 { get; set; }
        public string Taxk4 { get; set; }
        public string Taxk5 { get; set; }
        public string Taxk6 { get; set; }
        public string Taxk7 { get; set; }
        public string Taxk8 { get; set; }
        public string Taxk9 { get; set; }
        public decimal Netwr { get; set; }
        public string Zukri { get; set; }
        public string Ernam { get; set; }
        public string Erzet { get; set; }
        public string Erdat { get; set; }
        public string Stafo { get; set; }
        public string Kunrg { get; set; }
        public string Kunag { get; set; }
        public string Maber { get; set; }
        public string Stwae { get; set; }
        public string Exnum { get; set; }
        public string Stceg { get; set; }
        public string Aedat { get; set; }
        public string Sfakn { get; set; }
        public string Knuma { get; set; }
        public string FkartRl { get; set; }
        public string FkdatRl { get; set; }
        public string Kurst { get; set; }
        public string Mschl { get; set; }
        public string Mansp { get; set; }
        public string Spart { get; set; }
        public string Kkber { get; set; }
        public string Knkli { get; set; }
        public string Cmwae { get; set; }
        public decimal Cmkuf { get; set; }
        public string HitypPr { get; set; }
        public string BstnkVf { get; set; }
        public string Vbund { get; set; }
        public string FkartAb { get; set; }
        public string Kappl { get; set; }
        public string Landtx { get; set; }
        public string StcegH { get; set; }
        public string StcegL { get; set; }
        public string Xblnr { get; set; }
        public string Zuonr { get; set; }
        public decimal Mwsbk { get; set; }
        public string Logsys { get; set; }
        public string Fksto { get; set; }
        public string Xegdr { get; set; }
        public string Rplnr { get; set; }
        public string Lcnum { get; set; }
        public string J1afitp { get; set; }
        public string KurrfDat { get; set; }
        public string Akwae { get; set; }
        public decimal Akkur { get; set; }
        public string Kidno { get; set; }
        public string Bvtyp { get; set; }
        public string Numpg { get; set; }
        public string Bupla { get; set; }
        public string Vkont { get; set; }
        public string FkkDocstat { get; set; }
        public string Nrzas { get; set; }
        public string SpeBillingInd { get; set; }
        public string Vtref { get; set; }
        public string FkSourceSys { get; set; }
        public string FktypCrm { get; set; }
        public string Stgrd { get; set; }
        public string VbtypExt { get; set; }
        public string J1tpbupl { get; set; }
        public string DpcRel { get; set; }
        public string Mndid { get; set; }
        public string PayType { get; set; }
        public string Sepon { get; set; }
        public string Mndvg { get; set; }
        public string Sppaym { get; set; }
        public string Sppord { get; set; }
        public string Zzidprelista { get; set; }
        public string Procesado { get; set; }
    }
}
