using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesSap
{
    public partial class Vbrp
    {
        public string Mandt { get; set; }
        public string Vbeln { get; set; }
        public string Posnr { get; set; }
        public string Uepos { get; set; }
        public decimal Fkimg { get; set; }
        public string Vrkme { get; set; }
        public decimal Umvkz { get; set; }
        public decimal Umvkn { get; set; }
        public string Meins { get; set; }
        public decimal Smeng { get; set; }
        public decimal Fklmg { get; set; }
        public decimal Lmeng { get; set; }
        public decimal Ntgew { get; set; }
        public decimal Brgew { get; set; }
        public string Gewei { get; set; }
        public decimal Volum { get; set; }
        public string Voleh { get; set; }
        public string Gsber { get; set; }
        public string Prsdt { get; set; }
        public string Fbuda { get; set; }
        public decimal Kursk { get; set; }
        public decimal Netwr { get; set; }
        public string Vbelv { get; set; }
        public string Posnv { get; set; }
        public string Vgbel { get; set; }
        public string Vgpos { get; set; }
        public string Vgtyp { get; set; }
        public string Aubel { get; set; }
        public string Aupos { get; set; }
        public string Auref { get; set; }
        public string Matnr { get; set; }
        public string Arktx { get; set; }
        public string Pmatn { get; set; }
        public string Charg { get; set; }
        public string Matkl { get; set; }
        public string Pstyv { get; set; }
        public string Posar { get; set; }
        public string Prodh { get; set; }
        public string Vstel { get; set; }
        public string Atpkz { get; set; }
        public string Spart { get; set; }
        public string Pospa { get; set; }
        public string Werks { get; set; }
        public string Aland { get; set; }
        public string Wkreg { get; set; }
        public string Wkcou { get; set; }
        public string Wkcty { get; set; }
        public string Taxm1 { get; set; }
        public string Taxm2 { get; set; }
        public string Taxm3 { get; set; }
        public string Taxm4 { get; set; }
        public string Taxm5 { get; set; }
        public string Taxm6 { get; set; }
        public string Taxm7 { get; set; }
        public string Taxm8 { get; set; }
        public string Taxm9 { get; set; }
        public string Kowrr { get; set; }
        public string Prsfd { get; set; }
        public string Sktof { get; set; }
        public decimal Skfbp { get; set; }
        public string Kondm { get; set; }
        public string Ktgrm { get; set; }
        public string Kostl { get; set; }
        public string Bonus { get; set; }
        public string Provg { get; set; }
        public string Eannr { get; set; }
        public string Vkgrp { get; set; }
        public string Vkbur { get; set; }
        public string Spara { get; set; }
        public string Shkzg { get; set; }
        public string Ernam { get; set; }
        public string Erdat { get; set; }
        public string Erzet { get; set; }
        public string Bwtar { get; set; }
        public string Lgort { get; set; }
        public string Stafo { get; set; }
        public decimal Wavwr { get; set; }
        public decimal Kzwi1 { get; set; }
        public decimal Kzwi2 { get; set; }
        public decimal Kzwi3 { get; set; }
        public decimal Kzwi4 { get; set; }
        public decimal Kzwi5 { get; set; }
        public decimal Kzwi6 { get; set; }
        public decimal Stcur { get; set; }
        public string Uvprs { get; set; }
        public string Uvall { get; set; }
        public string Ean11 { get; set; }
        public string Prctr { get; set; }
        public string Kvgr1 { get; set; }
        public string Kvgr2 { get; set; }
        public string Kvgr3 { get; set; }
        public string Kvgr4 { get; set; }
        public string Kvgr5 { get; set; }
        public string Mvgr1 { get; set; }
        public string Mvgr2 { get; set; }
        public string Mvgr3 { get; set; }
        public string Mvgr4 { get; set; }
        public string Mvgr5 { get; set; }
        public string Matwa { get; set; }
        public decimal Bonba { get; set; }
        public string Kokrs { get; set; }
        public string Paobjnr { get; set; }
        public string PsPspPnr { get; set; }
        public string Aufnr { get; set; }
        public string Txjcd { get; set; }
        public decimal Cmpre { get; set; }
        public string Cmpnt { get; set; }
        public string Cuobj { get; set; }
        public string CuobjCh { get; set; }
        public string Koupd { get; set; }
        public string Uecha { get; set; }
        public string Xchar { get; set; }
        public string Abrvw { get; set; }
        public string Sernr { get; set; }
        public string BzirkAuft { get; set; }
        public string KdgrpAuft { get; set; }
        public string KondaAuft { get; set; }
        public string LlandAuft { get; set; }
        public string Mprok { get; set; }
        public string PltypAuft { get; set; }
        public string RegioAuft { get; set; }
        public string VkorgAuft { get; set; }
        public string VtwegAuft { get; set; }
        public string Abrbg { get; set; }
        public string Prosa { get; set; }
        public string Uepvw { get; set; }
        public string Autyp { get; set; }
        public string Stadat { get; set; }
        public string Fplnr { get; set; }
        public string Fpltr { get; set; }
        public string Aktnr { get; set; }
        public string KnumaPi { get; set; }
        public string KnumaAg { get; set; }
        public string Prefe { get; set; }
        public decimal Mwsbp { get; set; }
        public string AugruAuft { get; set; }
        public string Fareg { get; set; }
        public string Upmat { get; set; }
        public string Ukonm { get; set; }
        public double CmpreFlt { get; set; }
        public string Abfor { get; set; }
        public double Abges { get; set; }
        public string J1arfz { get; set; }
        public string J1aregio { get; set; }
        public string J1agicd { get; set; }
        public string J1adtyp { get; set; }
        public string J1atxrel { get; set; }
        public string J1bcfop { get; set; }
        public string J1btaxlw1 { get; set; }
        public string J1btaxlw2 { get; set; }
        public string J1btxsdc { get; set; }
        public decimal Brtwr { get; set; }
        public string Wktnr { get; set; }
        public string Wktps { get; set; }
        public string Rplnr { get; set; }
        public string KurskDat { get; set; }
        public string Wgru1 { get; set; }
        public string Wgru2 { get; set; }
        public string Kdkg1 { get; set; }
        public string Kdkg2 { get; set; }
        public string Kdkg3 { get; set; }
        public string Kdkg4 { get; set; }
        public string Kdkg5 { get; set; }
        public string Vkaus { get; set; }
        public string J1aindxp { get; set; }
        public string J1aidatep { get; set; }
        public string Kzfme { get; set; }
        public string Mwskz { get; set; }
        public string Vertt { get; set; }
        public string Vertn { get; set; }
        public string Sgtxt { get; set; }
        public string Delco { get; set; }
        public string Bemot { get; set; }
        public string Rrrel { get; set; }
        public decimal Akkur { get; set; }
        public string Wminr { get; set; }
        public string VgbelEx { get; set; }
        public string VgposEx { get; set; }
        public string Logsys { get; set; }
        public string VgtypEx { get; set; }
        public string J1btaxlw3 { get; set; }
        public string J1btaxlw4 { get; set; }
        public string J1btaxlw5 { get; set; }
        public string MsrId { get; set; }
        public string MsrRefundCode { get; set; }
        public string MsrRetReason { get; set; }
        public string NrabKnumh { get; set; }
        public decimal NrabValue { get; set; }
        public byte[] DisputeCase { get; set; }
        public byte[] FundUsageItem { get; set; }
        public string FarrReltype { get; set; }
        public string ClaimsTaxation { get; set; }
        public string KurrfDatOrig { get; set; }
        public string VgtypExt { get; set; }
        public string SgtRcat { get; set; }
        public string SgtScat { get; set; }
        public string Aufpl { get; set; }
        public string Aplzl { get; set; }
        public string Dpcnr { get; set; }
        public string Dcpnr { get; set; }
        public string Dpnrb { get; set; }
        public string PeropBeg { get; set; }
        public string PeropEnd { get; set; }
        public string Fonds { get; set; }
        public string Fistl { get; set; }
        public string Fkber { get; set; }
        public string GrantNbr { get; set; }
        public string PrsWorkPeriod { get; set; }
        public string Pprctr { get; set; }
        public string Pargb { get; set; }
        public string AufplOaa { get; set; }
        public string AplzlOaa { get; set; }
        public byte[] Campaign { get; set; }
        public string Compreas { get; set; }
        public string Zzbultos { get; set; }
        public string Zzcontrold { get; set; }
        public string Zzcontrolh { get; set; }
        public string Zzformatod { get; set; }
        public string Zzformatoh { get; set; }
        public string Zzidprelista { get; set; }
        public string Zzidregprelista { get; set; }
        public string Zzorden { get; set; }
        public short Zzcopy { get; set; }
    }
}
